"use strict";
const fs=require("node:fs"),path=require("node:path");
const thermal=require("../src/payload/app/thermal_v2.js"),pressure=require("../src/payload/app/pressure_solver.js"),profile=require("../src/payload/app/profile_state.js"),wear=require("../src/payload/app/wear_model.js"),integrity=require("../src/payload/app/integrity.js");
const knowledge=require("../knowledge/releases/ACLM_Tire_Knowledge_v1.7.0.json"),escortLive=require("./fixtures/telemetry/escort_v0100_ai_live_regression.json");
const APP_VERSION="0.10.1",LUT="0|0.75\n60|1.00\n100|0.92\n";
const specs=[
 {file:"brm_p48.json",car:"BRM P48",year:1960,familyId:"FAM003",classId:"CLS002",supplier:"Dunlop",supplierSourceIds:["FAM003"],mass:520,frontWeight:44,speed:205,front:{width:.096,radius:.304,rimRadius:.2032},rear:{width:.124,radius:.288,rimRadius:.1778}},
 {file:"ford_escort_rs1600.json",car:"Ford Escort RS1600",year:1974,familyId:"FAM023",classId:"CLS022",referenceDriver:"AI_REFERENCE",setupPressureControl:{min:15,max:50,step:1,source:"Kunos Escort setup.ini LF/RF/LR/RR pressure controls"},observedStart:{front:22.999,rear:23.005},mass:871,frontWeight:54,speed:205,front:{width:.205,radius:.300,rimRadius:.1651},rear:{width:.225,radius:.305,rimRadius:.1651}},
 {file:"ford_gt40.json",car:"Ford GT40",year:1967,familyId:"FAM022",classId:"CLS021",mass:1217,frontWeight:40,speed:315,front:{width:.230,radius:.325,rimRadius:.1905},rear:{width:.300,radius:.340,rimRadius:.1905}},
 {file:"group_c_porsche_962c.json",car:"Porsche 962C Group C fixture",year:1988,familyId:"FAM029",classId:"CLS028",mass:850,frontWeight:42,speed:350,front:{width:.300,radius:.335,rimRadius:.2286},rear:{width:.360,radius:.350,rimRadius:.2286}},
 {file:"1990s_bpr_gt_radial_fixture.json",car:"1990s BPR GT radial fixture",year:1995,familyId:"FAM010",classId:"CLS009",mass:1200,frontWeight:43,speed:300,front:{width:.285,radius:.335,rimRadius:.2286},rear:{width:.335,radius:.350,rimRadius:.2286}}
];
function buildFixture(spec){
 const family=knowledge.families.find(x=>x.id===spec.familyId),cls=knowledge.classes.find(x=>x.id===spec.classId),prior=knowledge.generatorPriors[spec.familyId];if(!family||!cls||!prior)throw new Error(`Fixture ${spec.file} has an unresolved knowledge dependency.`);
 const context={familyId:family.id,classId:cls.id,construction:family.construction,classFrom:cls.from,classTo:cls.to,familyFrom:family.from,familyTo:family.to,supplier:spec.supplier||null,supplierSourceIds:spec.supplierSourceIds||[],supportedSuppliers:spec.supplier?[spec.supplier]:[]};
 const state=profile.create("radial",profile.PROVENANCE.UNKNOWN_FALLBACK);profile.applyContext(state,context,"v0.10.1 static fixture");
 const construction=state.construction.value,totalN=spec.mass*9.80665,frontAxleN=totalN*spec.frontWeight/100,rearAxleN=totalN-frontAxleN,referenceDriver=spec.referenceDriver||pressure.REFERENCE_DRIVER.UNKNOWN;
 const thermalResults={},pressureResults={};let csp="[HEADER]\nVERSION=10\n\n[THERMAL_MODEL]\nVERSION=2\n\n[_EXTENSION]\nLATERAL_RAYS=2\nLONGITUDINAL_RAYS=4\nMAX_RAY_ANGLE=60\nDISABLE_RAY_DOUBLING=0\nSMOOTH_LOAD_SENS=1\n",vanilla="[HEADER]\nVERSION=10\n";
 for(const axle of ["front","rear"]){
  const g=spec[axle],load=(axle==="front"?frontAxleN:rearAxleN)/2,input={vehicleMass:spec.mass,frontWeight:spec.frontWeight,construction,era:spec.year,compound:"race",speedKph:spec.speed,confidence:.65,rollingResistance0:prior.rr0,rollingResistance1:prior.rr1,idealHotPressurePsi:prior.hotPsi,optimumTemperatureC:prior.tempOpt,axle,width:g.width,radius:g.radius,rimRadius:g.rimRadius,rate:prior.ratePerWidth*g.width*1000,sidewallStiffness:1,fz0:load*.9,expectedLoad:load,drivenDuty:axle==="rear"?1:0,brakeExposure:axle==="front"?.65:.35,pressurePsi:Math.max(15,prior.hotPsi-prior.coldDelta)},t=thermal.calculate(input);
  const options={familyId:family.id,axle,idealPsi:prior.hotPsi,ambientAirC:26,roadTemperatureC:36,referenceColdC:26,referenceDriver,referenceDuty:{familyId:family.id,classId:cls.id,driver:referenceDriver},setupPressureControl:spec.setupPressureControl||null,legacyTargetHotC:prior.tempOpt,targetHotC:prior.tempOpt,observedStartingPressurePsi:spec.observedStart?.[axle],inputs:{construction,compound:"race",widthM:g.width,estimatedInternalAirVolumeM3:t.estimates.internalVolume,referenceTireLoadN:load}},p=pressure.solveRecommendedColdPsi(options),report=pressure.pressureReport({...options,staticPsi:p.recommendedColdPsi,model:p});
  thermalResults[axle]=t;pressureResults[axle]={continuousColdPressurePsi:p.recommendedColdPsi,achievableSetupPressurePsi:p.achievableSetupColdPsi,observedSessionStartingPressurePsi:report.observedSessionStartingPressurePsi,idealPressurePsi:prior.hotPsi,containedAirEstimateC:p.predictedContainedAirC,initialStateEstimate:p.initialThermalState,volumeRatio:p.volumeModel.hotToColdVolumeRatio,volumeRatioProvenance:p.volumeModel.provenance,pressureUncertaintyC:p.containedAirModel.uncertaintyC,referenceDriver,model:p,report};
  csp+=thermal.renderLegacy(t,"race",axle,0,"temperature.lut")+"\n"+thermal.renderV2(t,axle,0)+"\n";vanilla+="\n"+thermal.renderLegacy(t,"race",axle,0,"temperature.lut")+"\n";
 }
 const files={"temperature.lut":LUT},cspAudit=thermal.inspectPackage(csp,files,1,true),vanillaAudit=thermal.inspectPackage(vanilla,files,1,false),life=wear.migrateLife(cls.menu[0],{sourceRefs:[family.id,cls.id]}),coherence=profile.validate(state,context,{year:spec.year,thermalConstruction:construction});
 const regressionAnchors=family.id==="FAM023"?{liveFixture:escortLive.fixtureId,oldGeneratedHotPsi:{fl:25.4,fr:23.6,rl:25.1,rr:23.9,classification:"FAIL"},sameTireCorrectedColdPsi:{fl:22,fr:23,rl:22,rr:23},sameTireCorrectedHotRangePsi:[26.6,27.5],generatorPolicy:"telemetry closure informs contained-air reference; exact track-side left/right pressures are not hard-coded"}:family.id==="FAM022"?{oldGeneratedReferencePsi:21.3,idealPsi:28,observedHotRangePsi:[23.1,24.7],classification:"FAIL",contamination:"old thermal/carcass telemetry used accidental radial construction and is excluded from fitting"}:null;
 const manifestFields={appVersion:APP_VERSION,knowledgeVersion:knowledge.releaseVersion,loggerVersion:APP_VERSION,year:spec.year,family:family.id,class:cls.id,compound:["race"],construction,constructionProvenance:state.construction,supplier:state.supplier.value,supplierProvenance:state.supplier,profileState:{authoritative:coherence.authoritative,coherence},requestedCondition:{airTemperatureC:26,roadTemperatureC:26,wearMultiplier:1,fuelRate:0,damageRate:0,sessionBlanketsEnabled:false},requestedTyreWearMultiplier:1,rawAidTireRate:null,aidTireRateInterpretation:"UNKNOWN",tireBlanketCapabilityTemperatureC:70,historicalBlanketRecommendation:{status:family.id==="FAM023"?"OFF":"UNRESOLVED"},requestedSessionBlanketsEnabled:false,carIniPhysicsVersion:"extended-2",tyresIniThermalVersion:2,tireFileSha256:integrity.sha256(csp),wearLutSha256:{representative:"FROZEN_BY_REGRESSION_TEST"},temperatureLutSha256:{"temperature.lut":integrity.sha256(LUT)},referenceDuty:{driver:referenceDriver},recommendedPressures:{front:pressureResults.front.report,rear:pressureResults.rear.report},pressureQuantizationMetadata:{front:pressureResults.front.report.setupPressureQuantization,rear:pressureResults.rear.report.setupPressureQuantization}};
 const diagnosticPrint={profileYear:spec.year,class:`${cls.id} ${cls.name}`,family:`${family.id} ${family.name}`,construction,constructionProvenance:state.construction,supplier:state.supplier.value,supplierProvenance:state.supplier,front:{continuousColdPressurePsi:pressureResults.front.continuousColdPressurePsi,achievableSetupPressurePsi:pressureResults.front.achievableSetupPressurePsi,idealPressurePsi:prior.hotPsi,containedAirEstimateC:pressureResults.front.containedAirEstimateC,initialStateEstimate:pressureResults.front.initialStateEstimate,volumeRatio:pressureResults.front.volumeRatio,volumeRatioProvenance:pressureResults.front.volumeRatioProvenance,pressureUncertaintyC:pressureResults.front.pressureUncertaintyC},rear:{continuousColdPressurePsi:pressureResults.rear.continuousColdPressurePsi,achievableSetupPressurePsi:pressureResults.rear.achievableSetupPressurePsi,idealPressurePsi:prior.hotPsi,containedAirEstimateC:pressureResults.rear.containedAirEstimateC,initialStateEstimate:pressureResults.rear.initialStateEstimate,volumeRatio:pressureResults.rear.volumeRatio,volumeRatioProvenance:pressureResults.rear.volumeRatioProvenance,pressureUncertaintyC:pressureResults.rear.pressureUncertaintyC},thermalV2Architecture:"legacy thermal sections plus CSP THERMAL_MODEL VERSION=2 and 2x4 ray network",lifeSemantics:life.lifeDefinition,manifestFields:Object.keys(manifestFields)};
 const result={schema:"ACLM v0.10.1 static cross-era fixture 1.1",appVersion:APP_VERSION,knowledgeVersion:knowledge.releaseVersion,identity:{car:spec.car,year:spec.year,familyId:family.id,classId:cls.id,familyName:family.name,className:cls.name},historicalProfile:{construction,constructionProvenance:state.construction,supplier:state.supplier.value,supplierProvenance:state.supplier,coherence},geometry:{vehicleMassKg:spec.mass,frontWeightPercent:spec.frontWeight,front:spec.front,rear:spec.rear},pressure:pressureResults,regressionAnchors,thermalConstruction:construction,thermal:thermalResults,wear:{historicalLife:life,referenceDuty:wear.referenceDutyFramework(),frozen:true},lutReferences:{temperature:["temperature.lut"],wear:"generated application wear LUT; v0.10.0 shape is frozen by regression hash"},telemetrySidecarCompatibility:{schema:"ACLM telemetry calibration manifest 1.1",manifestFields},packageManifest:manifestFields,diagnosticPrint,packageAudits:{csp:cspAudit,vanilla:vanillaAudit},generatedIni:{csp,vanilla}};
 result.fixtureSha256=integrity.sha256(JSON.stringify(result));return result;
}
function generate(output=path.join(__dirname,"fixtures","milestone5")){fs.mkdirSync(output,{recursive:true});const expected=new Set(specs.map(x=>x.file));for(const old of fs.readdirSync(output).filter(x=>x.endsWith(".json")&&x!=="fixture_index.json"&&!expected.has(x)))fs.rmSync(path.join(output,old));const fixtures=specs.map(buildFixture);for(let i=0;i<fixtures.length;i++)fs.writeFileSync(path.join(output,specs[i].file),JSON.stringify(fixtures[i],null,2)+"\n");fs.writeFileSync(path.join(output,"fixture_index.json"),JSON.stringify({schema:"ACLM v0.10.1 fixture index 1.1",appVersion:APP_VERSION,fixtures:fixtures.map((x,i)=>({car:x.identity.car,file:specs[i].file,sha256:x.fixtureSha256}))},null,2)+"\n");return fixtures;}
if(require.main===module){const fixtures=generate();for(const x of fixtures)console.log(JSON.stringify(x.diagnosticPrint));console.log(`generated ${fixtures.length} v${APP_VERSION} fixtures`);}
module.exports={APP_VERSION,specs,buildFixture,generate};
