"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),generator=require("./generate_milestone5_fixtures.js");
const fixtureDir=path.join(__dirname,"fixtures","milestone5"),fixtures=generator.generate(fixtureDir);
test("v0.10.1 cross-era fixture set is complete and both physics modes validate",()=>{assert.equal(fixtures.length,5);for(const x of fixtures){assert.equal(x.appVersion,"0.10.1");assert.equal(x.historicalProfile.coherence.pass,true,x.identity.car);assert.equal(x.packageAudits.csp.pass,true,x.identity.car+": "+x.packageAudits.csp.errors.join("; "));assert.equal(x.packageAudits.vanilla.pass,true,x.identity.car+": "+x.packageAudits.vanilla.errors.join("; "));assert.equal(x.pressure.front.report.volumeRatioProvenance,"UNKNOWN_ASSUMED_UNITY");assert.ok(x.pressure.front.report.predictedContainedAirHotTemperatureC);assert.ok(x.geometry.front.width);assert.ok(x.wear.historicalLife.lifeDefinition);assert.equal(x.telemetrySidecarCompatibility.schema,"ACLM telemetry calibration manifest 1.1");assert.ok(x.diagnosticPrint.front.continuousColdPressurePsi);assert.ok(x.diagnosticPrint.front.achievableSetupPressurePsi);assert.ok(x.diagnosticPrint.manifestFields.includes("supplierProvenance"));}});
test("GT40 cannot silently inherit the radial fallback",()=>{const x=fixtures.find(x=>x.identity.familyId==="FAM022");assert.equal(x.historicalProfile.construction,"bias");assert.ok(["AUTO_CLASSIFICATION","DIRECT_HISTORICAL_EVIDENCE"].includes(x.historicalProfile.constructionProvenance.provenance));assert.ok(x.historicalProfile.constructionProvenance.sourceIds.includes("ENG-EV-GT40-0001"));});
test("required Group C and 1990s GT radial generations remain distinct from period cross-ply",()=>{for(const id of ["FAM029","FAM010"])assert.equal(fixtures.find(x=>x.identity.familyId===id).historicalProfile.construction,"radial");assert.ok(fixtures.find(x=>x.identity.classId==="CLS028"));const gt40=fixtures.find(x=>x.identity.familyId==="FAM022"),bpr=fixtures.find(x=>x.identity.familyId==="FAM010");assert.notEqual(gt40.thermal.front.v2.carcassRollingK,bpr.thermal.front.v2.carcassRollingK);});
test("Escort and GT40 release-gate regressions retain their observed outcomes",()=>{const escort=fixtures.find(x=>x.identity.familyId==="FAM023"),gt40=fixtures.find(x=>x.identity.familyId==="FAM022");assert.equal(escort.regressionAnchors.oldGeneratedHotPsi.classification,"FAIL");assert.deepEqual(escort.regressionAnchors.sameTireCorrectedColdPsi,{fl:22,fr:23,rl:22,rr:23});assert.equal(gt40.regressionAnchors.classification,"FAIL");assert.match(gt40.regressionAnchors.contamination,/radial construction/);});
test("fixture outputs are static, indexed and free from personal paths",()=>{const index=JSON.parse(fs.readFileSync(path.join(fixtureDir,"fixture_index.json"),"utf8"));assert.equal(index.fixtures.length,5);for(const entry of index.fixtures){const text=fs.readFileSync(path.join(fixtureDir,entry.file),"utf8");assert.doesNotMatch(text,/C:\\Users\\|\/home\/[^/]+\//i);assert.equal(JSON.parse(text).fixtureSha256,entry.sha256);}});
test("Escort setup fixture exposes continuous, achievable and observed pressure independently",()=>{const x=fixtures.find(x=>x.identity.familyId==="FAM023"),f=x.pressure.front;assert.notEqual(f.continuousColdPressurePsi,f.achievableSetupPressurePsi);assert.equal(f.achievableSetupPressurePsi,24);assert.equal(f.observedSessionStartingPressurePsi,22.999);assert.equal(f.model.initialThermalState.source,"VALIDATED_AC_FIXTURE");});
