"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.join(__dirname,".."),profile=require(path.join(root,"src/payload/app/profile_state.js")),pressure=require(path.join(root,"src/payload/app/pressure_solver.js")),wear=require(path.join(root,"src/payload/app/wear_model.js")),integrity=require(path.join(root,"src/payload/app/integrity.js"));
require(path.join(root,"src/payload/app/validation_core.js"));const telemetry=globalThis.ACLMValidationCore;

test("FAM022 manual historical selection replaces stale radial fallback without overstating period evidence",()=>{const state=profile.create("radial",profile.PROVENANCE.UNKNOWN_FALLBACK),ctx={familyId:"FAM022",classId:"CLS021",construction:"mixed"};profile.applyContext(state,ctx,"manual family selection");assert.equal(state.construction.value,"bias");assert.equal(state.construction.provenance,profile.PROVENANCE.AUTO_CLASSIFICATION);const result=profile.validate(state,ctx,{thermalConstruction:"bias"});assert.equal(result.pass,true);assert.equal(result.evidence.categories.construction.status,profile.EVIDENCE_STATUS.RECONSTRUCTED);});
test("explicit radial override remains visible and warns instead of becoming a silent default",()=>{const state=profile.create("bias",profile.PROVENANCE.FAMILY_DEFAULT),ctx={familyId:"FAM022",classId:"CLS021",construction:"mixed"};profile.setConstruction(state,"radial",profile.PROVENANCE.USER_EXPLICIT_OVERRIDE);const result=profile.validate(state,ctx,{thermalConstruction:"radial"});assert.equal(result.pass,true);assert.equal(result.issues[0].code,"HISTORICAL_PROFILE_CONFLICT");assert.equal(result.issues[0].severity,"WARNING");});
test("unsupported stale construction blocks generation",()=>{const state=profile.create("radial",profile.PROVENANCE.UNKNOWN_FALLBACK),ctx={familyId:"FAM023",classId:"CLS022",construction:"bias"},result=profile.validate(state,ctx,{thermalConstruction:"radial"});assert.equal(result.pass,false);assert.equal(result.issues[0].severity,"BLOCK");});
test("knowledge construction audit covers every family",()=>{const k=JSON.parse(fs.readFileSync(path.join(root,"knowledge/releases/ACLM_Tire_Knowledge_v1.7.0.json"),"utf8")),rows=profile.auditKnowledge(k);assert.equal(rows.length,k.families.length);assert.equal(rows.find(x=>x.familyId==="FAM022").generatedConstruction,"bias");});
test("absolute-pressure formula exposes volume assumption and physically meaningful directions",()=>{const base={idealPsi:27,referenceColdC:26,inputs:{widthM:.22,estimatedInternalAirVolumeM3:.03,referenceTireLoadN:2500,construction:"radial"}},r=pressure.solveRecommendedColdPsi(base),larger=pressure.predictHotPsi(r.recommendedColdPsi,r.predictedContainedAirC,26,pressure.ATM_PSI,1.02,1),smaller=pressure.predictHotPsi(r.recommendedColdPsi,r.predictedContainedAirC,26,pressure.ATM_PSI,.98,1);assert.equal(r.volumeModel.provenance,"UNKNOWN_ASSUMED_UNITY");assert.ok(larger<r.predictedHotPsi);assert.ok(smaller>r.predictedHotPsi);});
test("Escort correction closes and old GT40 GOOD classification is rejected",()=>{const escort=pressure.solveRecommendedColdPsi({familyId:"FAM023",axle:"front",idealPsi:27,referenceColdC:26,legacyTargetHotC:84.5,inputs:{construction:"bias",widthM:.205,estimatedInternalAirVolumeM3:.026,referenceTireLoadN:2300}});assert.ok(escort.recommendedColdPsi>22&&escort.recommendedColdPsi<23.2);assert.equal(escort.classification,"PASS");assert.equal(pressure.classifyClosure(24.2-28),"FAIL");});
test("construction, volume, load and cavity temperature affect pressure screening",()=>{const base={idealPsi:28,referenceColdC:26,inputs:{widthM:.25,estimatedInternalAirVolumeM3:.04,referenceTireLoadN:2600}},bias=pressure.solveRecommendedColdPsi({...base,inputs:{...base.inputs,construction:"bias"}}),radial=pressure.solveRecommendedColdPsi({...base,inputs:{...base.inputs,construction:"radial"}}),loaded=pressure.solveRecommendedColdPsi({...base,inputs:{...base.inputs,construction:"bias",referenceTireLoadN:3600}}),small=pressure.solveRecommendedColdPsi({...base,inputs:{...base.inputs,construction:"bias",estimatedInternalAirVolumeM3:.02}});assert.notEqual(bias.predictedContainedAirC,radial.predictedContainedAirC);assert.ok(loaded.predictedContainedAirC>bias.predictedContainedAirC);assert.ok(small.predictedContainedAirC>bias.predictedContainedAirC);});
test("wear threshold inversion interpolates and preserves plateau ambiguity",()=>{const curve=[[0,100],[5,100],[10,98],[20,90]],x=wear.crossingAtGrip(curve,95),plateau=wear.crossingAtGrip(curve,100);assert.equal(x.status,"INTERPOLATED");assert.equal(x.x,13.75);assert.equal(plateau.status,"AMBIGUOUS_PLATEAU_RANGE");assert.deepEqual(plateau.range,[0,5]);});
test("life migration separates abrasion, provisional and competitive meanings",()=>{const abrasion=wear.migrateLife({lifeKm:450,lifeBasis:"abrasion/service durability evidence"}),prior=wear.migrateLife({lifeKm:130,lifeBasis:"Generator calibration prior; replace with event evidence"}),competitive=wear.migrateLife({lifeKm:90,lifeBasis:"competitive grip life"});assert.equal(abrasion.abrasionLifeKm,450);assert.equal(abrasion.competitiveLifeKm,null);assert.equal(prior.lifeDefinition,"PROVISIONAL_GENERATOR_PRIOR");assert.equal(competitive.competitiveLifeKm,90);assert.notEqual(wear.referenceDutyFramework().acImplementation.virtualKm,"historical real km");});
test("telemetry wear selects tire-set distance and excludes logger cumulative distance",()=>{const csv="logger_cumulative_distance_m,session_distance_m,stint_distance_m,tire_set_distance_m,wear_raw_fl,wear_raw_fr,wear_raw_rl,wear_raw_rr\n100000,0,0,0,100,100,100,100\n110000,10000,8000,6000,99.9,99.9,99.8,99.8\n",summary=telemetry.telemetrySummary(telemetry.parseTelemetry(csv));assert.equal(summary.wear.realDistanceBasis,"CURRENT_TIRE_SET_DISTANCE");assert.equal(summary.wear.realDistanceKm,6);assert.equal(summary.wear.persistentLoggerDistanceExcludedFromWearCalibration,true);});
test("new session resets calibration distances while persistent logger distance remains non-zero",()=>{const csv=fs.readFileSync(path.join(root,"tests/fixtures/telemetry/distance_reset_nonzero_logger_regression.csv"),"utf8"),summary=telemetry.telemetrySummary(telemetry.parseTelemetry(csv));assert.equal(summary.wear.realDistanceBasis,"CURRENT_TIRE_SET_DISTANCE");assert.equal(summary.wear.realDistanceKm,10);assert.equal(summary.wear.distanceSpans.LOGGER_CUMULATIVE_DISTANCE.km,10);assert.equal(summary.wear.persistentLoggerDistanceExcludedFromWearCalibration,true);});
test("wear landmarks include plateau end and terminal/failure",()=>{const marks=wear.landmarks([[0,100],[5,100],[10,98],[20,50]]);assert.equal(marks[0].landmark,"PLATEAU_END");assert.equal(marks[0].x,5);assert.equal(marks.at(-1).landmark,"TERMINAL_OR_FAILURE");assert.equal(marks.at(-1).grip,50);});
test("integrity helper returns a deterministic SHA-256",()=>assert.equal(integrity.sha256("abc"),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
