$ErrorActionPreference = "Stop"
$AppDir = Join-Path $PSScriptRoot "app"
$Port = 48765
$CurrentVersion = "0.5.6"
$KnowledgeManifestUrl = "https://raw.githubusercontent.com/aclmproject/tire_lab/main/knowledge/ACLM_Tire_Knowledge_latest.json"
$AppManifestUrl = "https://raw.githubusercontent.com/aclmproject/tire_lab/main/manifests/ACLM_Tire_Lab_latest.json"
$UpdatesPage = "https://github.com/aclmproject/tire_lab/releases"
$KnowledgeCache = Join-Path $PSScriptRoot "knowledge_cache.json"
$KnowledgeFallback = Join-Path $AppDir "knowledge_fallback.json"
$listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback,$Port)
try { $listener.Start() } catch { exit 0 }
function Mime([string]$p){switch([IO.Path]::GetExtension($p).ToLowerInvariant()){'.html'{"text/html; charset=utf-8"}'.js'{"text/javascript; charset=utf-8"}'.css'{"text/css; charset=utf-8"}'.json'{"application/json; charset=utf-8"}'.webmanifest'{"application/manifest+json; charset=utf-8"}'.png'{"image/png"}default{"application/octet-stream"}}}
function JsonBytes($obj){[Text.Encoding]::UTF8.GetBytes(($obj|ConvertTo-Json -Depth 12 -Compress))}
function HashText([string]$text){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Get-JsonUrl([string]$Url){$r=Invoke-WebRequest -UseBasicParsing -Uri $Url -TimeoutSec 20 -Headers @{'Cache-Control'='no-cache'};return [string]$r.Content}
function Read-Knowledge([string]$Path,[string]$Source){$raw=Get-Content -Raw -Encoding UTF8 $Path;$obj=$raw|ConvertFrom-Json;if(!$obj.schemaVersion -or !$obj.releaseVersion -or !$obj.families -or !$obj.classes){throw 'Invalid ACLM knowledge release.'};return @{release=$obj;source=$Source}}
function Current-Knowledge{try{if(Test-Path $KnowledgeCache -PathType Leaf){return Read-Knowledge $KnowledgeCache 'last-known-good cache'}}catch{};return Read-Knowledge $KnowledgeFallback 'bundled fallback'}
function Sync-Knowledge([bool]$Force=$false){$current=Current-Knowledge;$m=(Get-JsonUrl $KnowledgeManifestUrl)|ConvertFrom-Json;if(!$m.version -or !$m.download_url -or !$m.sha256){throw 'Knowledge manifest is incomplete.'};$cv=[version]([string]$current.release.releaseVersion);$rv=[version]([string]$m.version);if(!$Force -and $rv -le $cv){return @{release=$current.release;source=$current.source;updated=$false}};$raw=Get-JsonUrl ([string]$m.download_url);if((HashText $raw) -ne ([string]$m.sha256).ToLowerInvariant()){throw 'Knowledge release failed SHA-256 verification.'};$obj=$raw|ConvertFrom-Json;if(!$obj.schemaVersion -or ([string]$obj.schemaVersion).Split('.')[0] -ne '1' -or !$obj.releaseVersion -or !$obj.families -or !$obj.classes){throw 'Unsupported or invalid knowledge release.'};Set-Content -Path $KnowledgeCache -Value $raw -Encoding UTF8;return @{release=$obj;source='verified online knowledge';updated=$true}}
function App-UpdateInfo{try{$m=(Get-JsonUrl $AppManifestUrl)|ConvertFrom-Json;return @{version=$m.version;file_name=$m.file_name;published_utc=$m.published_utc;notes=$m.notes;current_version=$CurrentVersion;updates_folder=$UpdatesPage;release_page=$UpdatesPage}}catch{return @{version=$CurrentVersion;current_version=$CurrentVersion;updates_folder=$UpdatesPage;release_page=$UpdatesPage;warning=$_.Exception.Message}}}
while($true){$client=$listener.AcceptTcpClient();try{$stream=$client.GetStream();$reader=New-Object IO.StreamReader($stream,[Text.Encoding]::UTF8,$false,4096,$true);$line=$reader.ReadLine();if(!$line){$client.Close();continue};$headers=@{};while(($h=$reader.ReadLine()) -ne $null -and $h -ne ''){$ix=$h.IndexOf(':');if($ix -gt 0){$headers[$h.Substring(0,$ix).Trim().ToLowerInvariant()]=$h.Substring($ix+1).Trim()}};$parts=$line.Split(' ');$method=$parts[0];$url=$parts[1].Split('?')[0];
if($url -eq '/api/knowledge-current'){try{$k=Current-Knowledge;$body=JsonBytes @{release=$k.release;source=$k.source};$code='200 OK'}catch{$body=JsonBytes @{error=$_.Exception.Message};$code='500 Internal Server Error'};$mime='application/json; charset=utf-8'}
elseif($url -eq '/api/knowledge-sync' -and $method -eq 'POST'){try{$k=Sync-Knowledge $true;$body=JsonBytes @{release=$k.release;source=$k.source;updated=$k.updated};$code='200 OK'}catch{$body=JsonBytes @{error=$_.Exception.Message};$code='503 Service Unavailable'};$mime='application/json; charset=utf-8'}
elseif($url -eq '/api/update-info'){$body=JsonBytes (App-UpdateInfo);$code='200 OK';$mime='application/json; charset=utf-8'}
elseif($url -eq '/api/install-update'){$body=JsonBytes @{error='Automatic application installation is disabled. Open the release page and download updates in your browser.';manual_only=$true;release_page=$UpdatesPage};$code='409 Conflict';$mime='application/json; charset=utf-8'}
else{$rel=[Uri]::UnescapeDataString($url.TrimStart('/'));if([string]::IsNullOrWhiteSpace($rel)){$rel='index.html'};$rel=$rel.Replace('/',[IO.Path]::DirectorySeparatorChar);$full=[IO.Path]::GetFullPath((Join-Path $AppDir $rel));$root=[IO.Path]::GetFullPath($AppDir);if(!$full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)-or !(Test-Path $full -PathType Leaf)){$body=[Text.Encoding]::UTF8.GetBytes('404');$code='404 Not Found';$mime='text/plain; charset=utf-8'}else{$body=[IO.File]::ReadAllBytes($full);$code='200 OK';$mime=Mime $full}};$head="HTTP/1.1 $code`r`nContent-Type: $mime`r`nContent-Length: $($body.Length)`r`nCache-Control: no-store`r`nConnection: close`r`n`r`n";$hb=[Text.Encoding]::ASCII.GetBytes($head);$stream.Write($hb,0,$hb.Length);if($method -ne 'HEAD'){$stream.Write($body,0,$body.Length)};$stream.Flush()}catch{}finally{$client.Close()}}
