(function(root){
"use strict";
const PROVENANCE=Object.freeze({FAMILY_DEFAULT:"FAMILY_DEFAULT",DIRECT_HISTORICAL_EVIDENCE:"DIRECT_HISTORICAL_EVIDENCE",AUTO_CLASSIFICATION:"AUTO_CLASSIFICATION",IMPORTED_EXISTING_PHYSICS:"IMPORTED_EXISTING_PHYSICS",USER_EXPLICIT_OVERRIDE:"USER_EXPLICIT_OVERRIDE",UNKNOWN_FALLBACK:"UNKNOWN_FALLBACK"});
const EVIDENCE_STATUS=Object.freeze({DIRECTLY_SOURCED:"DIRECTLY SOURCED",PARTIALLY_SOURCED:"PARTIALLY SOURCED",RECONSTRUCTED:"RECONSTRUCTED",PROVISIONAL:"PROVISIONAL",UNKNOWN:"UNKNOWN"});
const OVERRIDES=Object.freeze({FAM022:Object.freeze({construction:"bias",provenance:PROVENANCE.AUTO_CLASSIFICATION,sourceIds:Object.freeze(["ENG-EV-GT40-0001"]),confidence:"required internal FAM022 compatibility resolution; the cited engineering record is a software-regression record, not direct period construction evidence"})});
function normalizeConstruction(value){const s=String(value||"").trim().toLowerCase();if(/bias|cross/.test(s))return "bias";if(/radial/.test(s))return "radial";return null;}
function normalizeSupplier(value){const s=String(value||"").trim();return !s||/^(general\s*\/\s*unknown|unknown)$/i.test(s)?"General / unknown":s;}
function familyConstruction(context){if(!context)return {value:null,provenance:PROVENANCE.UNKNOWN_FALLBACK,sourceIds:[],confidence:"unresolved"};const override=OVERRIDES[String(context.familyId||"").toUpperCase()];if(override)return {...override,value:override.construction};const value=normalizeConstruction(context.construction);return value?{value,provenance:PROVENANCE.FAMILY_DEFAULT,sourceIds:[context.familyId,context.classId].filter(Boolean),confidence:context.confidenceSource||"knowledge-family default"}:{value:null,provenance:PROVENANCE.UNKNOWN_FALLBACK,sourceIds:[context.familyId,context.classId].filter(Boolean),confidence:"mixed/unknown construction requires explicit evidence or user review"};}
function supplierRecord(value="General / unknown",provenance=PROVENANCE.UNKNOWN_FALLBACK,details={}){return {value:normalizeSupplier(value),provenance,sourceIds:[...(details.sourceIds||[])],confidence:details.confidence||"unresolved",reason:details.reason||"supplier state initialized",explicit:provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE};}
function create(initialValue="radial",provenance=PROVENANCE.UNKNOWN_FALLBACK,initialSupplier="General / unknown"){return {construction:{value:normalizeConstruction(initialValue)||"radial",provenance,sourceIds:[],confidence:"unresolved default",explicit:false},supplier:supplierRecord(initialSupplier,PROVENANCE.UNKNOWN_FALLBACK),familyId:null,classId:null,lastTransition:"initial"};}
function setConstruction(state,value,provenance,details={}){const normalized=normalizeConstruction(value);if(!normalized)throw new Error("Unsupported construction value: "+value);state.construction={value:normalized,provenance,sourceIds:[...(details.sourceIds||[])],confidence:details.confidence||"unspecified",explicit:provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE};state.lastTransition=details.reason||"construction update";return state;}
function setSupplier(state,value,provenance,details={}){state.supplier=supplierRecord(value,provenance,details);state.lastTransition=details.reason||"supplier update";return state;}
function contextSupplier(context){const value=normalizeSupplier(context?.supplier);if(value!=="General / unknown")return supplierRecord(value,PROVENANCE.DIRECT_HISTORICAL_EVIDENCE,{sourceIds:[...(context?.supplierSourceIds||context?.sourceIds||[])],confidence:context?.supplierConfidence||"context supplier evidence",reason:"supplier resolved from historical context"});return supplierRecord();}
function applyContext(state,context,reason="historical context changed"){
 const previousFamily=state.familyId,previousClass=state.classId;state.familyId=context?.familyId||null;state.classId=context?.classId||null;const intended=familyConstruction(context);let constructionChanged=false,supplierChanged=false;
 if(state.construction?.provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE)state.lastTransition=reason+"; explicit construction override retained";
 else if(intended.value){setConstruction(state,intended.value,intended.provenance,{sourceIds:intended.sourceIds,confidence:intended.confidence,reason});constructionChanged=true;}
 else setConstruction(state,state.construction?.value||"radial",PROVENANCE.UNKNOWN_FALLBACK,{sourceIds:intended.sourceIds,confidence:intended.confidence,reason});
 const supplied=contextSupplier(context),transitioned=previousFamily!==state.familyId||previousClass!==state.classId;
 if(supplied.value!=="General / unknown"&&state.supplier?.provenance!==PROVENANCE.USER_EXPLICIT_OVERRIDE){setSupplier(state,supplied.value,supplied.provenance,supplied);supplierChanged=true;}
 else if(transitioned&&state.supplier?.provenance!==PROVENANCE.USER_EXPLICIT_OVERRIDE){setSupplier(state,"General / unknown",PROVENANCE.UNKNOWN_FALLBACK,{sourceIds:[state.familyId,state.classId].filter(Boolean),confidence:"cleared on class/family transition; no supplier evidence for the new context",reason});supplierChanged=true;}
 state.lastTransition=reason+(state.supplier?.provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE?"; explicit supplier override retained":"");return {state,intended,changed:constructionChanged||supplierChanged,constructionChanged,supplierChanged};
}
function numericRange(context){const classFrom=Number(context?.classFrom),classTo=Number(context?.classTo),familyFrom=Number(context?.familyFrom),familyTo=Number(context?.familyTo);return {classFrom:Number.isFinite(classFrom)?classFrom:null,classTo:Number.isFinite(classTo)?classTo:null,familyFrom:Number.isFinite(familyFrom)?familyFrom:null,familyTo:Number.isFinite(familyTo)?familyTo:null};}
function citationIds(values){return [...new Set((values||[]).map(String).filter(Boolean).filter(x=>!/^FAM\d+$/i.test(x)&&!/^CLS\d+$/i.test(x)))];}
function evidenceCategory(status,sourceIds=[],basis="",limitation=""){return {status,sourceIds:citationIds(sourceIds),basis,limitation};}
function historicalEvidenceAudit(state,context,options={}){
 const constructionSources=citationIds(state?.construction?.sourceIds),supplierSources=citationIds(state?.supplier?.sourceIds),contextSources=citationIds(context?.sourceIds);
 const categories={
  carIdentity:evidenceCategory(options.carIdentitySourceIds?.length?EVIDENCE_STATUS.DIRECTLY_SOURCED:EVIDENCE_STATUS.PROVISIONAL,options.carIdentitySourceIds,options.carIdentitySourceIds?.length?"imported AC package identity":"user-entered or inferred identity","AC package identity is not proof of period specification"),
  classFamily:evidenceCategory(contextSources.length?EVIDENCE_STATUS.PARTIALLY_SOURCED:context?EVIDENCE_STATUS.RECONSTRUCTED:EVIDENCE_STATUS.UNKNOWN,contextSources,context?`${context.classId||"class unknown"} / ${context.familyId||"family unknown"}`:"no historical context","internal FAM/CLS identifiers are not citations"),
  construction:evidenceCategory(state?.construction?.provenance===PROVENANCE.DIRECT_HISTORICAL_EVIDENCE&&constructionSources.length?EVIDENCE_STATUS.DIRECTLY_SOURCED:state?.construction?.value?EVIDENCE_STATUS.RECONSTRUCTED:EVIDENCE_STATUS.UNKNOWN,constructionSources,state?.construction?.provenance||PROVENANCE.UNKNOWN_FALLBACK,"profile compatibility does not prove a numerical construction model"),
  supplier:evidenceCategory(state?.supplier?.value&&state.supplier.value!=="General / unknown"?(supplierSources.length?EVIDENCE_STATUS.DIRECTLY_SOURCED:EVIDENCE_STATUS.PROVISIONAL):EVIDENCE_STATUS.UNKNOWN,supplierSources,state?.supplier?.provenance||PROVENANCE.UNKNOWN_FALLBACK,"supplier stays unknown without event/car-specific evidence"),
  geometry:evidenceCategory(options.geometrySourceIds?.length?EVIDENCE_STATUS.PARTIALLY_SOURCED:EVIDENCE_STATUS.PROVISIONAL,options.geometrySourceIds,options.geometrySourceIds?.length?"imported AC geometry with traceable source":"generator/imported reconstruction","sim geometry is not automatically period dimensional evidence"),
  compound:evidenceCategory(contextSources.length?EVIDENCE_STATUS.PARTIALLY_SOURCED:EVIDENCE_STATUS.RECONSTRUCTED,contextSources,"class/family compound menu","exact compound properties remain reconstruction unless directly documented"),
  temperature:evidenceCategory(EVIDENCE_STATUS.PROVISIONAL,options.temperatureSourceIds||[],options.temperatureSourceIds?.length?"generator prior plus identified simulator telemetry":"generator prior; no host-specific live telemetry yet","simulator closure is not historical optimum evidence"),
  pressure:evidenceCategory(options.pressureEvidenceStatus||EVIDENCE_STATUS.PROVISIONAL,options.pressureSourceIds||[],options.pressureSourceIds?.length?"reference-duty pressure model plus identified live closure":"reference-duty pressure model only; host remains unvalidated","a static software prediction is not a validated live result or automatically a historical racing-pressure source"),
  wearLife:evidenceCategory(options.wearEvidenceStatus||EVIDENCE_STATUS.RECONSTRUCTED,options.wearSourceIds||[],options.wearSourceIds?.length?"family prior plus identified stint/durability evidence":"generator family prior; host-specific life unresolved","period durability evidence must not be converted directly into AC virtual-km wear without telemetry calibration")
 };
 const statuses=Object.values(categories).map(x=>x.status),hasDirect=statuses.includes(EVIDENCE_STATUS.DIRECTLY_SOURCED)||statuses.includes(EVIDENCE_STATUS.PARTIALLY_SOURCED),hasModel=statuses.some(x=>[EVIDENCE_STATUS.RECONSTRUCTED,EVIDENCE_STATUS.PROVISIONAL,EVIDENCE_STATUS.UNKNOWN].includes(x));
 const overall=hasDirect&&hasModel?EVIDENCE_STATUS.PARTIALLY_SOURCED:statuses.every(x=>x===EVIDENCE_STATUS.DIRECTLY_SOURCED)?EVIDENCE_STATUS.DIRECTLY_SOURCED:statuses.includes(EVIDENCE_STATUS.RECONSTRUCTED)?EVIDENCE_STATUS.RECONSTRUCTED:statuses.includes(EVIDENCE_STATUS.PROVISIONAL)?EVIDENCE_STATUS.PROVISIONAL:EVIDENCE_STATUS.UNKNOWN;
 return {schema:"ACLM historical evidence status 1.0",overall,categories,rule:"PROFILE COHERENCE checks compatibility only. Historical evidence status reports sourcing separately; internal FAM/CLS IDs are not citations."};
}
function validate(state,context,options={}){
 const intended=familyConstruction(context),actual=normalizeConstruction(state?.construction?.value),provenance=state?.construction?.provenance||PROVENANCE.UNKNOWN_FALLBACK,supplier=state?.supplier||supplierRecord(options.supplier),range=numericRange(context),year=Number(options.year),override=options.allowAnachronisticOverride===true;
 const fields={year:Number.isFinite(year)?year:null,classId:context?.classId||null,familyId:context?.familyId||null,classPeriod:[range.classFrom,range.classTo],familyPeriod:[range.familyFrom,range.familyTo],familyConstruction:intended.value,currentConstruction:actual,constructionProvenance:provenance,supplier:supplier.value,supplierProvenance:supplier.provenance,compound:options.compound||null,geometry:options.geometry||null,thermalConstruction:normalizeConstruction(options.thermalConstruction)||actual,anachronisticOverride:override};const issues=[];
 if(!context)issues.push({code:"PROFILE_UNRESOLVED",severity:"REVIEW",message:"Historical family/class is unresolved."});
 if(context&&Number.isFinite(year)){const classConflict=range.classFrom!==null&&range.classTo!==null&&(year<range.classFrom||year>range.classTo),familyConflict=range.familyFrom!==null&&range.familyTo!==null&&(year<range.familyFrom||year>range.familyTo);if(classConflict||familyConflict){const valid=[classConflict?`class ${range.classFrom}-${range.classTo}`:null,familyConflict?`family ${range.familyFrom}-${range.familyTo}`:null].filter(Boolean).join(" and ");issues.push({code:"YEAR_PROFILE_CONFLICT",severity:override?"WARNING":"BLOCK",message:`Year ${year} is outside the selected ${valid}.`,supportedOverride:override});}}
 if(context&&intended.value&&actual&&intended.value!==actual){const supported=provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE||provenance===PROVENANCE.DIRECT_HISTORICAL_EVIDENCE;issues.push({code:"HISTORICAL_PROFILE_CONFLICT",severity:supported?"WARNING":"BLOCK",message:`Historical family requires ${intended.value}; current construction is ${actual} (${provenance}).`,supportedOverride:supported});}
 if(actual&&fields.thermalConstruction&&actual!==fields.thermalConstruction)issues.push({code:"THERMAL_CONSTRUCTION_CONFLICT",severity:"BLOCK",message:`Generated construction ${actual} does not match Thermal V2 construction ${fields.thermalConstruction}.`});
 const supportedSuppliers=(context?.supportedSuppliers||[]).map(normalizeSupplier).filter(x=>x!=="General / unknown"),knownSupplier=supplier.value!=="General / unknown";
 if(knownSupplier&&supportedSuppliers.length&&!supportedSuppliers.some(x=>x.toLowerCase()===supplier.value.toLowerCase()))issues.push({code:"SUPPLIER_PROFILE_CONFLICT",severity:supplier.provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE?"WARNING":"BLOCK",message:`Supplier ${supplier.value} is not supported by the selected profile evidence (${supportedSuppliers.join(", ")}).`,supportedOverride:supplier.provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE});
 else if(knownSupplier&&supplier.provenance===PROVENANCE.UNKNOWN_FALLBACK)issues.push({code:"STALE_SUPPLIER_STATE",severity:"BLOCK",message:`Supplier ${supplier.value} has no provenance after the class/year transition.`});
 else if(knownSupplier&&supplier.provenance===PROVENANCE.USER_EXPLICIT_OVERRIDE&&!supportedSuppliers.length)issues.push({code:"SUPPLIER_EXPLICIT_UNVERIFIED",severity:"WARNING",message:`Supplier ${supplier.value} is an explicit user override; the selected profile has no supplier-specific evidence.`});
 const pass=!issues.some(x=>x.severity==="BLOCK"),profileCoherent=pass&&!override&&!issues.some(x=>["PROFILE_UNRESOLVED","SUPPLIER_EXPLICIT_UNVERIFIED","SUPPLIER_PROFILE_CONFLICT","HISTORICAL_PROFILE_CONFLICT"].includes(x.code)),authoritative=profileCoherent,title=!pass?"PROFILE COHERENCE FAIL":override?"PROFILE COHERENCE PASS — ANACHRONISTIC / CUSTOM":issues.length?"PROFILE COHERENCE PASS — REVIEW":"PROFILE COHERENCE PASS",evidence=historicalEvidenceAudit(state,context,options);return {pass,profileCoherent,authoritative,compatibilityOnly:true,title,historicalEvidenceStatus:evidence.overall,evidence,fields,issues,intended};
}
function auditKnowledge(release,generatedResolver){const families=Array.isArray(release?.families)?release.families:[],classes=Array.isArray(release?.classes)?release.classes:[];return families.map(f=>{const related=classes.filter(c=>c.familyId===f.id),override=OVERRIDES[f.id],canonical=override?.construction||normalizeConstruction(f.construction),profileValues=[...new Set(related.map(c=>normalizeConstruction(c.construction)||"unknown"))],profileConstruction=profileValues.length===1?profileValues[0]:profileValues.join("/"),generated=generatedResolver?normalizeConstruction(generatedResolver(f,related)):canonical,thermal=generated;let mismatch="PASS";if(!canonical)mismatch="KNOWN_TO_FALLBACK / REVIEW";else if(generated!==canonical)mismatch=`${canonical.toUpperCase()} -> ${(generated||"unknown").toUpperCase()}`;else if(related.some(c=>normalizeConstruction(c.construction)&&normalizeConstruction(c.construction)!==canonical))mismatch="CLASS/FAMILY CONFLICT / REVIEW";return {familyId:f.id,historicalClass:related.map(c=>`${c.id} ${c.name}`).join(" | ")||"family only",canonicalConstruction:canonical||"mixed/unknown",confidence:override?.confidence||f.constructionConfidence||f.historicalAbsoluteConfidence||"knowledge default; numeric confidence unavailable",source:(override?.sourceIds||f.sourceIds||[]).join(", ")||"knowledge family record",profileConstruction,generatedConstruction:generated||"unknown fallback",thermalConstruction:thermal||"unknown fallback",mismatchStatus:mismatch};});}
const api={PROVENANCE,EVIDENCE_STATUS,OVERRIDES,normalizeConstruction,normalizeSupplier,familyConstruction,create,setConstruction,setSupplier,applyContext,historicalEvidenceAudit,validate,auditKnowledge};if(typeof module!=="undefined"&&module.exports)module.exports=api;root.ACLMProfileState=api;
})(typeof window!=="undefined"?window:globalThis);
