"use strict";
(function(){
 const core=window.ACLMValidationCore;if(!core)return;
 const state={track:null,telemetry:null,simulation:null,balance:[],sweep:[],strategy:[],comparison:null,testProfile:null,research:[]},e=id=>document.getElementById(id),esc=s=>escapeHtml(String(s??"")),num=id=>Number(e(id)?.value);
 function table(headers,rows){return "<table><thead><tr>"+headers.map(x=>"<th>"+esc(x)+"</th>").join("")+"</tr></thead><tbody>"+rows.map(r=>"<tr>"+r.map(x=>"<td>"+esc(x)+"</td>").join("")+"</tr>").join("")+"</tbody></table>";}
 function download(name,data,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type:type||"application/json"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200);}
 function selectedModelCompounds(){return selectedCompounds().map(key=>{const prior=activeFamilyPrior(),base=key==="soft"?1.08:key==="hard"?.92:1;return {key,name:compoundDisplayName(key),target:targetTempForCompound(key),loadF:loadDuty("front").intensity,loadR:loadDuty("rear").intensity,cool:prior&&dryCompound(key)?Number(prior.cool):base,lifeKm:historicalLifeKm(key)};});}
 function drawTelemetry(){const c=e("telemetryOverlay"),summary=state.telemetry;if(!c||!summary)return;const rect=c.getBoundingClientRect(),w=Math.max(420,Math.floor(rect.width||650)),h=230,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle="#0b1016";ctx.fillRect(0,0,w,h);const pts=summary.points;if(!pts.length){ctx.fillStyle="#9aa7b5";ctx.fillText("No mapped tire-temperature columns",20,30);return;}const vals=pts.flatMap(p=>[p.front,p.rear]).filter(Number.isFinite),min=Math.min(...vals)-3,max=Math.max(...vals)+3,x0=45,y0=20,pw=w-65,ph=h-55;ctx.strokeStyle="#34404d";for(let i=0;i<=4;i++){const y=y0+ph*i/4;ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x0+pw,y);ctx.stroke();}function series(key,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();let started=false;pts.forEach((p,i)=>{if(!Number.isFinite(p[key]))return;const x=x0+pw*i/Math.max(1,pts.length-1),y=y0+ph-(p[key]-min)/(max-min)*ph;if(!started){ctx.moveTo(x,y);started=true;}else ctx.lineTo(x,y);});ctx.stroke();}series("front","#43b4ff");series("rear","#ffb347");ctx.fillStyle="#dbe5ef";ctx.fillText("Telemetry tire temperature — front (blue) / rear (orange)",x0,14);ctx.fillText(min.toFixed(0)+" C",5,y0+ph);ctx.fillText(max.toFixed(0)+" C",5,y0+8);}
 async function importTrack(){const file=e("trackZip")?.files?.[0];if(!file)return;e("trackStatus").textContent="Reading track ZIP...";try{const files=await readZipPhysics(file);state.track=core.parseTrackFiles(files,file.name);const t=state.track;e("trackStatus").innerHTML="<span class=\"ok\"><b>Track parsed:</b></span> "+esc(t.name)+" · "+t.lengthKm.toFixed(3)+" km ("+esc(t.lengthSource)+") · "+t.surfaceCount+" surfaces · mean friction "+t.meanFriction.toFixed(3)+" · inferred energy "+t.energyScore.toFixed(2)+".<br><span class=\"muted\">Direct: "+esc(t.directEvidence.join("; "))+". Inferred: "+esc(t.inferredEvidence.join("; "))+".</span>";e("trackName").value=t.name;e("trackLength").value=t.lengthKm.toFixed(3);e("trackEnergy").value=t.energyScore.toFixed(2);}catch(err){e("trackStatus").innerHTML="<span class=\"error\">"+esc(err.message)+"</span>";}}
 function importTelemetryText(text,label){try{const parsed=core.parseTelemetry(text);state.telemetry=core.telemetrySummary(parsed);const s=state.telemetry;e("telemetryStatus").innerHTML="<span class=\"ok\"><b>Telemetry mapped:</b></span> "+s.rows+" rows · "+s.tempHeaders.length+" temperature columns · confidence "+esc(s.mappingConfidence)+" · average "+(Number.isFinite(s.averageTemperature)?s.averageTemperature.toFixed(1)+" C":"unavailable")+" · "+esc(label||"CSV")+".";drawTelemetry();renderEvidence();return s;}catch(err){e("telemetryStatus").innerHTML="<span class=\"error\">"+esc(err.message)+"</span>";throw err;}}
 async function importTelemetry(){const file=e("telemetryCsv")?.files?.[0];if(!file)return;importTelemetryText(await file.text(),file.name);}
 function currentTrack(){return state.track||{name:e("trackName").value||"Manual track",lengthKm:num("trackLength")||4,energyScore:num("trackEnergy")||1,lengthSource:"manual",meanFriction:1,surfaceCount:0};}
 function runSimulation(){const compounds=selectedModelCompounds();if(!compounds.length){e("simulationResults").innerHTML="<span class=\"error\">Select a compound.</span>";return;}state.simulation=core.simulateThermal({track:currentTrack(),laps:num("simLaps"),avgSpeed:num("simSpeed"),ambient:num("simAmbient"),trackTemp:num("simTrackTemp"),aggression:num("simAggression"),blankets:n("blankets"),compounds});state.balance=core.balanceRecommendations(state.simulation);e("simulationResults").innerHTML=table(["Compound","Axle","Target","Warm lap","Peak","Finish","Assessment"],state.simulation.rows.map(r=>[r.name,r.axle,r.target.toFixed(0)+" C",r.warmLap??"not reached",r.peak+" C",r.end+" C",r.status]));e("balanceResults").innerHTML=table(["Compound","F-R finish","Assessment","Recommendation"],state.balance.map(x=>[compoundDisplayName(x.compound),x.delta+" C",x.status,x.recommendation]));runStrategy();renderEvidence();}
 function runSweep(){const comp=e("sweepCompound").value||selectedCompounds()[0]||"medium",target=targetTempForCompound(comp);state.sweep=core.pressureCamberSweep({idealHot:n("pIdeal"),referenceTemp:n("pRefTemp"),targetTemp:target,coldPressure:pressure(comp,e("sweepAxle").value),camber:num(e("sweepAxle").value==="front"?"validationCamberF":"validationCamberR"),construction:v("construction")});e("sweepResults").innerHTML=table(["Cold psi","Camber","Predicted hot psi","Screening score"],state.sweep.map(x=>[x.coldPsi,x.camberDeg+"°",x.predictedHotPsi,x.score]));}
 function runStrategy(){const comps=selectedModelCompounds().map(c=>{const row=state.simulation?.rows.find(r=>r.compound===c.key&&r.axle==="front");return {...c,warmLap:row?.warmLap};});state.strategy=core.stintStrategy({trackKm:currentTrack().lengthKm,laps:num("simLaps"),compounds:comps});e("strategyResults").innerHTML=table(["Compound","Life input","Recommended stint","Stops","Warm-up","Confidence"],state.strategy.map(x=>[x.name,x.lifeKm+" km",x.recommendedLaps+" laps",x.stops,x.warmupLaps??"not reached",x.confidence]));}
 async function comparePacks(){const a=e("compareZipA").files?.[0],b=e("compareZipB").files?.[0];if(!a||!b)return;try{state.comparison=core.compareTirePacks(await readZipPhysics(a),await readZipPhysics(b));const d=state.comparison;e("compareResults").innerHTML="<b>"+d.differenceCount+" differing tyres.ini values.</b>"+table(["Section","Key",a.name,b.name],d.differences.slice(0,80).map(x=>[x.section,x.key,x.a,x.b]));}catch(err){e("compareResults").innerHTML="<span class=\"error\">"+esc(err.message)+"</span>";}}
 function renderEvidence(){const rows=[["Car identity",v("car")||"unresolved",provenanceLabel("car"),provenanceLabel("car")==="Direct AC package"?"high":"review"],["Series/class",v("series")||"unresolved",activeHistoricalContext?"knowledge class/family":"manual/unresolved",activeHistoricalContext?"medium":"low"],["Tire supplier",v("supplier")||"unresolved",provenanceLabel("supplier"),/unknown/i.test(v("supplier"))?"low":"review"],["Generator prior",activeHistoricalContext?.familyId||"none",activeFamilyPrior()?"reconstruction prior":"default",activeFamilyPrior()?"medium":"low"],["Track identity",state.track?.name||"not imported",state.track?"track ZIP metadata":"manual",state.track?"high":"low"],["Track energy",currentTrack().energyScore.toFixed(2),state.track?"derived from track files":"manual",state.track?"medium":"low"],["Telemetry",state.telemetry?state.telemetry.rows+" rows":"not imported",state.telemetry?"user CSV":"none",state.telemetry?.mappingConfidence||"low"]];e("evidenceResults").innerHTML=table(["Item","Value","Provenance","Confidence"],rows);}
 function populateTests(){const sel=e("testProfile");core.TEST_CARS.forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=p.name+" ("+p.year+")";sel.appendChild(o);});}
 function applyTest(){const p=core.TEST_CARS.find(x=>x.id===e("testProfile").value);if(!p)return;state.testProfile=p;const set=(id,val)=>{if(e(id))e(id).value=val;};set("car",p.name);set("year",p.year);set("mass",p.mass);set("frontWeight",p.frontWeight);set("fzFactor",p.fzFactor);set("fw",p.fw);set("rw",p.rw);set("construction",p.construction);const cls=runtimeClasses().find(c=>p.seriesKeywords.some(k=>c.name.toLowerCase().includes(k)));if(cls){setMenuValue("series",cls.name);const ctx=window.ACLMHistoricalCategories?.contextForClass?.(cls.id,p.year);if(ctx){e("preset").value=ctx.familyId;applyHistoricalContext(ctx,"validation test profile");}}else setMenuValue("series",GENERAL_UNKNOWN);refreshLoadDutyStatus();refreshSolvedPressures();renderTireGraphs();renderEvidence();e("testExpected").innerHTML="<b>Expected behavior:</b> "+esc(p.expected)+"<br><b>Current static duty:</b> "+esc(loadDutySummary())+".";}
 function loadResearch(){try{state.research=JSON.parse(localStorage.getItem("aclm-research-review-v1")||"[]");if(!Array.isArray(state.research))state.research=[];}catch(err){state.research=[];}renderResearch();}
 function saveResearch(){try{localStorage.setItem("aclm-research-review-v1",JSON.stringify(state.research));}catch(err){}renderResearch();}
 function addResearch(){const entry={id:"EV-"+Date.now(),car:v("car"),year:v("year"),series:v("series"),supplier:v("supplier"),sourceUrl:e("researchUrl").value.trim(),summary:e("researchSummary").value.trim(),publicEvidence:e("researchPublic").checked,status:"draft",createdUtc:new Date().toISOString(),history:[{utc:new Date().toISOString(),action:"draft created",actor:"local user"}]};if(!entry.sourceUrl||!entry.summary){e("researchPacketStatus").innerHTML="<span class=\"error\">Source URL and evidence summary are required.</span>";return;}state.research.push(entry);saveResearch();e("researchPacketStatus").innerHTML="<span class=\"ok\">Draft evidence added locally.</span>";}
 function advanceResearch(id){const x=state.research.find(r=>r.id===id);if(!x)return;const next=x.status==="draft"?"reviewed-locally":"ready-for-maintainer-review";x.status=next;x.history.push({utc:new Date().toISOString(),action:next,actor:"local user"});saveResearch();}
 function renderResearch(){e("researchReviewResults").innerHTML=state.research.length?table(["ID","Source","Status","History"],state.research.map(x=>[x.id,x.sourceUrl,x.status,x.history.length])):"<span class=\"muted\">No local research drafts.</span>";}
 function exportResearch(){const packets=state.research.map(x=>core.researchPacket({...x,history:undefined},x.history));download("ACLM_Community_Research_Submissions.json",JSON.stringify({submissions:packets},null,2));}
 function workspaceSnapshot(){return {product:"ACLM Tire Lab Validation Workspace",schemaVersion:"1.0.0",generatedUtc:new Date().toISOString(),car:v("car"),series:v("series"),track:state.track,telemetry:state.telemetry?{rows:state.telemetry.rows,mappingConfidence:state.telemetry.mappingConfidence,averageTemperature:state.telemetry.averageTemperature}:null,simulation:state.simulation,balance:state.balance,sweep:state.sweep,strategy:state.strategy,testProfile:state.testProfile,researchDraftCount:state.research.length,limitations:["screening simulation only","track KN5 geometry is not decoded","telemetry is authoritative only when channel mapping and sensor units are verified"]};}
 function installBuildExport(){if(typeof build!=="function")return;const original=build;build=function(){const files=original();files["ACLM_VALIDATION_WORKSPACE.json"]=JSON.stringify(workspaceSnapshot(),null,2)+"\n";return files;};if(typeof buildHistoricalReportData==="function"){const reportBase=buildHistoricalReportData;buildHistoricalReportData=function(comps){const d=reportBase(comps);d.model.push({label:"Validation track",value:currentTrack().name+" / energy "+currentTrack().energyScore.toFixed(2)});if(state.simulation)d.findings.push("Reduced-order track simulation completed for "+state.simulation.laps+" laps; results require telemetry calibration.");return d;};}}
 e("trackZip").addEventListener("change",importTrack);e("telemetryCsv").addEventListener("change",importTelemetry);e("runTrackSimulation").addEventListener("click",runSimulation);e("runSweep").addEventListener("click",runSweep);e("runStrategy").addEventListener("click",runStrategy);e("comparePacks").addEventListener("click",comparePacks);e("applyTestProfile").addEventListener("click",applyTest);e("addResearchDraft").addEventListener("click",addResearch);e("advanceResearch").addEventListener("click",()=>{const id=state.research.at(-1)?.id;if(id)advanceResearch(id);});e("exportResearchPackets").addEventListener("click",exportResearch);["trackLength","trackEnergy","simLaps","simSpeed","simAmbient","simTrackTemp","simAggression"].forEach(id=>e(id).addEventListener("input",renderEvidence));
 populateTests();loadResearch();installBuildExport();renderEvidence();runSweep();window.ACLMValidationWorkspace={state,runSimulation,workspaceSnapshot,importTelemetryText};
})();
