"use strict";
(function(root){
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,Number(x)));
 const finite=x=>Number.isFinite(Number(x));
 const mean=a=>a.length?a.reduce((s,x)=>s+Number(x),0)/a.length:NaN;
 const basename=p=>String(p||"").replace(/\\/g,"/").split("/").filter(Boolean).pop()?.toLowerCase()||"";
 function csvLine(line,delimiter){const out=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&quoted&&line[i+1]==='"'){value+='"';i++;}else if(ch==='"')quoted=!quoted;else if(ch===delimiter&&!quoted){out.push(value.trim());value="";}else value+=ch;}out.push(value.trim());return out;}
 function parseTelemetry(text){
  const lines=String(text||"").replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error("Telemetry CSV needs a header and at least one data row.");
  const first=lines[0],delimiters=[",",";","\t"],delimiter=delimiters.sort((a,b)=>(first.split(b).length-first.split(a).length))[0],headers=csvLine(first,delimiter).map((h,i)=>h||("column_"+i));
  const rows=lines.slice(1).map(line=>csvLine(line,delimiter)).filter(r=>r.length>1).map(values=>{const row={};headers.forEach((h,i)=>row[h]=values[i]??"");return row;});return {delimiter,headers,rows};
 }
 function findHeader(headers,patterns){return headers.find(h=>patterns.some(p=>p.test(String(h).toLowerCase())))||null;}
 const WHEELS=Object.freeze(["fl","fr","rl","rr"]);
 const THERMAL_NETWORK_KEYS=Object.freeze(["SURFACE_TO_CARCASS","CARCASS_TO_SURFACE","CARCASS_TO_CORE","CORE_TO_CARCASS","CORE_TO_AMBIENT","SURFACE_TO_AMBIENT","COOL_FACTOR","CARCASS_ROLLING_K"]);
 const PRESSURE_COMPLIANCE_KEYS=Object.freeze(["RATE","FLEX","FLEX_GAIN","PRESSURE_STATIC","PRESSURE_IDEAL","PRESSURE_SPRING_GAIN","PRESSURE_FLEX_GAIN","PRESSURE_D_GAIN"]);
 const COUPLED_NETWORK_DIAGNOSTIC="surface heating present; low core equilibrium may be caused by the surface/carcass/core transfer and/or heat rejection balance rather than insufficient friction heat generation.";
 function percentile(values,q){const a=values.map(Number).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const p=clamp(q,0,1)*(a.length-1),lo=Math.floor(p),hi=Math.ceil(p);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(p-lo);}
 function stats(values){const a=values.map(Number).filter(Number.isFinite);return {count:a.length,mean:mean(a),minimum:a.length?Math.min(...a):NaN,maximum:a.length?Math.max(...a):NaN,p95:percentile(a,.95)};}
 function columnValues(dataset,header,rows){if(!header)return [];return (rows||dataset.rows).map(r=>Number(r[header])).filter(Number.isFinite);}
 function wheelHeader(headers,wheel,predicate){const re=new RegExp("(?:^|_)"+wheel+"(?:_|$)","i");return headers.find(h=>re.test(h)&&predicate(String(h).toLowerCase()))||null;}
 function distanceSpanKm(dataset){const h=findHeader(dataset.headers,[/^distance_traveled_m$/,/^session_distance_m$/,/^distance.*_m$/]);if(!h)return {header:null,km:NaN};const a=columnValues(dataset,h);return {header:h,km:a.length?(Math.max(...a)-Math.min(...a))/1000:NaN};}
 function virtualDistanceSpanKm(dataset){const h=findHeader(dataset.headers,[/^virtual.*km$/,/^virt.*km$/,/^vkm$/]);if(!h)return {header:null,km:NaN};const a=columnValues(dataset,h);return {header:h,km:a.length?Math.max(...a)-Math.min(...a):NaN};}
 function normalizationMultiplier(dataset,fallback){const h=findHeader(dataset.headers,[/^aid_tire_rate$/,/^aidtyrerate$/,/^tyre_wear_multiplier$/,/^tire_wear_multiplier$/]),a=columnValues(dataset,h),m=finite(mean(a))&&mean(a)>0?mean(a):(finite(fallback)&&Number(fallback)>0?Number(fallback):1);return {header:h,value:m,source:h?"recorded AC aidTireRate":"user-declared fallback"};}
 function wearAnalysis(dataset,options){
  const real=distanceSpanKm(dataset),virtual=virtualDistanceSpanKm(dataset),mult=normalizationMultiplier(dataset,options?.wearMultiplier),wheels={},classification=String(options?.wearTestClassification||"clean-stint"),incidentAbuse=/incident|abuse/i.test(classification),nominalExposure=finite(real.km)?real.km*mult.value:NaN;
  for(const wheel of WHEELS){const header=wheelHeader(dataset.headers,wheel,h=>/wear/.test(h));if(!header)continue;const rows=dataset.rows.filter(r=>finite(r[header])),values=rows.map(r=>Number(r[header]));if(!values.length)continue;const delta=values.at(-1)-values[0],change=Math.abs(delta),normalizedDelta=incidentAbuse?NaN:delta/mult.value,exitIndex=values.findIndex((x,i)=>i>0&&x!==values[0]);let exitReal=NaN;if(exitIndex>0&&real.header&&finite(rows[exitIndex]?.[real.header])){const distances=rows.map(r=>Number(r[real.header])).filter(Number.isFinite);exitReal=(Number(rows[exitIndex][real.header])-Math.min(...distances))/1000;}wheels[wheel]={header,startRaw:values[0],endRaw:values.at(-1),startRawText:String(rows[0][header]),endRawText:String(rows.at(-1)[header]),minimumRaw:Math.min(...values),maximumRaw:Math.max(...values),deltaFromStartRaw:delta,absoluteChangeRaw:change,changePerRealKm:finite(real.km)&&real.km>0?change/real.km:NaN,changePerVirtualKm:finite(virtual.km)&&virtual.km>0?change/virtual.km:NaN,firstPlateauExitRealKm:exitReal,firstPlateauExitNominalExposureKm:finite(exitReal)?exitReal*mult.value:NaN,normalized1xDeltaEstimate:normalizedDelta,normalized1xChangePerRealKmEstimate:!incidentAbuse&&finite(real.km)&&real.km>0?Math.abs(normalizedDelta)/real.km:NaN};}
  return {rawValuesPreserved:true,roundingApplied:false,testClassification:classification,incidentAbuse,realDistanceKm:real.km,realDistanceHeader:real.header,virtualDistanceKm:virtual.km,virtualDistanceHeader:virtual.header,aidTireRate:mult.value,multiplierSource:mult.source,nominalMultiplierNormalizedExposureKm:nominalExposure,nominalExposureLabel:"NOMINAL MULTIPLIER-NORMALIZED EXPOSURE — NOT A DIRECT HISTORICAL LIFE ESTIMATE.",mechanismDistinction:["normal-distance wear","load-sensitive wear","slip/abuse-sensitive wear","thermal-abuse wear","WEAR_CURVE grip degradation"],incidentInterpretation:incidentAbuse?"Incident/abuse evidence is compatible with USE_LOAD=1 causing slow effective wear in normal running and much faster effective virtual-km accumulation during large slip/temperature events; it is not a normal stint-life calibration.":null,wheels,normalization:{method:incidentAbuse?"no grip-health delta normalization for incident/abuse data":"first-order observed raw delta divided by recorded/declarative wear multiplier",isEstimate:mult.value!==1,deltaNormalizationAllowed:!incidentAbuse,warning:incidentAbuse?"Incident-generated slip and thermal abuse are nonlinear. Do not divide final grip-health loss by the multiplier or infer historical life.":"Accelerated-wear normalization assumes approximately linear multiplier behavior. It is an estimate, not a direct 1x measurement."}};
 }
 function conditionSummary(dataset,requested){
  const air=findHeader(dataset.headers,[/^air_temp_c$/,/air.*temp/]),road=findHeader(dataset.headers,[/^road_temp_c$/,/road.*temp/,/track.*temp/]),observed={airTempC:stats(columnValues(dataset,air)),roadTempC:stats(columnValues(dataset,road))};
  return {requested:{airTempC:finite(requested?.airTempC)?Number(requested.airTempC):null,roadTempC:finite(requested?.roadTempC)?Number(requested.roadTempC):null},observed,source:"recorded AC physics telemetry is authoritative for actual test conditions",mismatchIsRejection:false};
 }
 function thermalDiagnostic(dataset,options){
  const lateCount=Math.max(1,Math.ceil(dataset.rows.length*.20)),lateRows=dataset.rows.slice(-lateCount),perWheel={},coreMeans=[],surfaceP95=[];
  for(const wheel of WHEELS){const core=wheelHeader(dataset.headers,wheel,h=>/core/.test(h)&&/temp/.test(h)),surface=dataset.headers.filter(h=>new RegExp("(?:^|_)"+wheel+"(?:_|$)","i").test(h)&&/temp/.test(h)&&!/(core|brake|disc|rotor)/.test(h));const coreStats=stats(columnValues(dataset,core,lateRows)),surfaceStats=stats(surface.flatMap(h=>columnValues(dataset,h,lateRows)));perWheel[wheel]={coreHeader:core,surfaceHeaders:surface,lateCore:coreStats,lateSurface:surfaceStats};if(finite(coreStats.mean))coreMeans.push(coreStats.mean);if(finite(surfaceStats.p95))surfaceP95.push(surfaceStats.p95);}
  const intended=options?.intendedTemperatureWindow||null,coreMean=mean(coreMeans),surface95=mean(surfaceP95),surfaceHeatingPresent=finite(surface95)&&finite(coreMean)&&surface95-coreMean>=7,lowCore=!!intended&&finite(coreMean)&&finite(intended.low)&&coreMean<Number(intended.low)-3;
  return {classification:surfaceHeatingPresent&&lowCore?COUPLED_NETWORK_DIAGNOSTIC:(surfaceHeatingPresent?"surface heating present; compare the core equilibrium with the intended historical window before changing heat generation.":"insufficient evidence to classify the surface/core heat balance."),surfaceHeatingPresent,lowCoreVersusIntendedWindow:lowCore,lateCoreMeanC:coreMean,lateSurfaceP95C:surface95,intendedTemperatureWindow:intended,perWheel,networkAudit:[...THERMAL_NETWORK_KEYS],frictionConclusion:"Do not increase FRICTION_K from this pattern alone.",coefficientDecision:"hold: diagnostic evidence only; no global or family coefficient retune"};
 }
 function pressureAudit(summary,options){
  const pressures=[],perWheel={};for(const wheel of WHEELS){const h=wheelHeader(summary.datasetHeaders||[],wheel,x=>/(press|psi)/.test(x)),observed=h&&summary._dataset?stats(columnValues(summary._dataset,h,summary._lateRows)):stats([]);if(observed.count)pressures.push(...columnValues(summary._dataset,h,summary._lateRows));const ideal=finite(options?.idealPressurePsi)?Number(options.idealPressurePsi):NaN,error=finite(ideal)&&finite(observed.mean)?observed.mean-ideal:NaN;perWheel[wheel]={header:h,observedStabilizedPsi:observed,hotPressureErrorPsi:error,classification:root.ACLMPressure?.classifyClosure?root.ACLMPressure.classifyClosure(error):(Math.abs(error)<=.5?"GOOD":Math.abs(error)<=1.5?"REVIEW":finite(error)?"FAIL / pressure model mismatch":"UNRESOLVED")};}
  const observed=stats(pressures),ideal=finite(options?.idealPressurePsi)?Number(options.idealPressurePsi):NaN,cold=options?.generatedColdPressurePsi||null,evidence=options?.pressureEvidence||null,isBrm=Array.isArray(evidence?.sourceIds)&&evidence.sourceIds.includes("M131"),classes=Object.values(perWheel).map(x=>x.classification),overall=classes.some(x=>/^FAIL/.test(x))?"FAIL / pressure model mismatch":classes.some(x=>x==="REVIEW")?"REVIEW":classes.some(x=>x==="GOOD")?"GOOD":"UNRESOLVED",ab=options?.pressureAB||{},unsafe=ab.role==="baseline"&&ab.unsafeBaseline===true;
  return {observedStabilizedPsi:observed,perWheel,overallClosureClassification:overall,generatedPressureIdealPsi:ideal,generatedColdPressurePsi:cold,gapBelowIdealPsi:finite(ideal)&&finite(observed.mean)?ideal-observed.mean:NaN,hotPressureErrorDefinition:"stabilized pressure - PRESSURE_IDEAL",closureThresholdsPsi:{good:0.5,review:1.5,failAbove:1.5},generatedPressureReport:options?.generatedPressureReport||null,complianceAuditKeys:[...PRESSURE_COMPLIANCE_KEYS],complianceParameters:options?.complianceParameters||null,abTest:{role:ab.role||"unclassified",tirePackId:String(ab.tirePackId||"").trim(),coldPressureAdjustmentPsi:ab.coldPressureAdjustmentPsi||null,subjectiveFeedback:ab.subjectiveFeedback||"",unsafeBaseline:unsafe},safetyFlag:unsafe?"GENERATED BASELINE UNSAFE FOR CONTINUED HIGH-SPEED VALIDATION":null,evidence,assessment:isBrm?"For the BRM/R5 case, a ~20 psi generated start matches the current Dunlop ~500 kg guide, while its 24 psi hot guide is below the generated 26 psi ideal. That makes an over-high PRESSURE_IDEAL the leading pressure-only hypothesis; direct 1960 BRM pressure evidence and thermal/pressure coupling remain unresolved.":"Pressure closure and compliance must be audited together. A several-psi deficit can reduce grip and increase compliance; do not assume PRESSURE_STATIC is the only cause.",decision:isBrm?"hold BRM pressure values; the completed 5x incident run does not resolve the pressure question":"hold generator values pending a same-tire pressure-corrected A/B comparison"};
 }
 function comparisonMetrics(dataset,summary){const perWheel={};for(const wheel of WHEELS){const load=wheelHeader(dataset.headers,wheel,h=>/load/.test(h)),slipAngle=wheelHeader(dataset.headers,wheel,h=>/slip.?angle/.test(h)),wheelSlip=wheelHeader(dataset.headers,wheel,h=>/slip/.test(h)&&!/angle/.test(h));perWheel[wheel]={pressurePsi:summary.pressureAudit.perWheel[wheel]?.observedStabilizedPsi||stats([]),coreTempC:summary.thermalDiagnostic.perWheel[wheel]?.lateCore||stats([]),surfaceTempC:summary.thermalDiagnostic.perWheel[wheel]?.lateSurface||stats([]),loadN:stats(columnValues(dataset,load,summary._lateRows)),slipAngle:stats(columnValues(dataset,slipAngle,summary._lateRows)),wheelSlip:stats(columnValues(dataset,wheelSlip,summary._lateRows)),wearDeltaRaw:summary.wear.wheels[wheel]?.deltaFromStartRaw??NaN};}const lat=findHeader(dataset.headers,[/^accg_lat$/,/lateral.*acc/,/^lat.*g$/]),steer=findHeader(dataset.headers,[/^steering$/,/steer.*angle/,/^steer$/]);return {perWheel,lateralAccelerationG:stats(columnValues(dataset,lat,summary._lateRows)),steering:stats(columnValues(dataset,steer,summary._lateRows)),slipAngleAvailability:Object.values(perWheel).some(x=>x.slipAngle.count>0)?"recorded channel":"not exposed by standard AC shared memory; requires another verified source"};}
 function comparePressureAB(a,b){if(!a||!b)return null;const perWheel={};for(const wheel of WHEELS){const ap=a.pressureAudit?.perWheel?.[wheel],bp=b.pressureAudit?.perWheel?.[wheel],am=a.comparisonMetrics?.perWheel?.[wheel]||{},bm=b.comparisonMetrics?.perWheel?.[wheel]||{};perWheel[wheel]={baselineHotPressureErrorPsi:ap?.hotPressureErrorPsi??NaN,correctedHotPressureErrorPsi:bp?.hotPressureErrorPsi??NaN,closureImprovementPsi:finite(ap?.hotPressureErrorPsi)&&finite(bp?.hotPressureErrorPsi)?Math.abs(ap.hotPressureErrorPsi)-Math.abs(bp.hotPressureErrorPsi):NaN,baselineCoreC:am.coreTempC?.mean??NaN,correctedCoreC:bm.coreTempC?.mean??NaN,baselineSurfaceC:am.surfaceTempC?.mean??NaN,correctedSurfaceC:bm.surfaceTempC?.mean??NaN,baselineLoadN:am.loadN?.mean??NaN,correctedLoadN:bm.loadN?.mean??NaN,baselineWheelSlip:am.wheelSlip?.mean??NaN,correctedWheelSlip:bm.wheelSlip?.mean??NaN,baselineSlipAngle:am.slipAngle?.mean??NaN,correctedSlipAngle:bm.slipAngle?.mean??NaN,baselineWearDeltaRaw:am.wearDeltaRaw??NaN,correctedWearDeltaRaw:bm.wearDeltaRaw??NaN};}const aId=a.pressureAudit?.abTest?.tirePackId||"",bId=b.pressureAudit?.abTest?.tirePackId||"",sameTireVerified=!!aId&&aId===bId,correctedGood=Object.values(b.pressureAudit?.perWheel||{}).every(x=>x.classification==="GOOD");return {sameTireRequired:true,sameTireVerified,tirePackId:sameTireVerified?aId:null,allowedChange:"cold pressure only",perWheel,baselineSubjective:a.pressureAudit?.abTest?.subjectiveFeedback||"",correctedSubjective:b.pressureAudit?.abTest?.subjectiveFeedback||"",correctedPressureClosureGood:correctedGood,decision:!sameTireVerified?"A/B decision blocked until both runs identify the same tire pack.":correctedGood?"If excessive compliance is substantially improved, prioritize cold-pressure prediction/pressure-rise correction. Otherwise continue the coupled carcass audit; do not raise pressures arbitrarily.":"Corrected run has not yet closed to the generated ideal; do not decide between pressure prediction and carcass compliance."};}
 function analyzeCalibrationFixture(fixture){
  const runs=fixture?.runs||[],warm=runs.find(x=>x.warmers===true),cold=runs.find(x=>x.warmers===false),wheels=WHEELS,delta={};let maxDelta=0;for(const w of wheels){const a=Number(warm?.equilibriumCoreC?.[w]),b=Number(cold?.equilibriumCoreC?.[w]);delta[w]=Math.abs(a-b);if(finite(delta[w]))maxDelta=Math.max(maxDelta,delta[w]);}
  const startGap=Math.abs(Number(warm?.startingCoreC)-Number(cold?.startingCoreC)),converged=startGap>=20&&maxDelta<=2,surfaceHeating=Object.values(fixture?.lateRun?.wheels||{}).some(x=>Number(x.surfaceP95C)-Number(x.coreC)>=7);
  return {fixtureId:fixture?.fixtureId||null,converged,startGapC:startGap,maxEquilibriumDeltaC:maxDelta,equilibriumDeltaByWheelC:delta,classification:converged&&surfaceHeating?COUPLED_NETWORK_DIAGNOSTIC:"fixture does not yet prove warm/cold convergence with surface heating",networkAudit:[...THERMAL_NETWORK_KEYS],frictionConclusion:"Do not increase FRICTION_K from this A/B result alone.",coefficientDecision:"hold",pressureAudit:fixture?.pressureAudit||null,wearAudit:fixture?.wear||null};
 }
 function telemetrySummary(dataset,options={}){
  const h=dataset.headers,xHeader=findHeader(h,[/^distance/,/lap.?distance/,/^time/,/^lap$/]),speedHeader=findHeader(h,[/^speed/,/vehicle.?speed/,/velocity/]);
  const wheelPattern=/(tyre|tire|wheel|fl|fr|rl|rr|front|rear)/i,tempHeaders=h.filter(x=>/(temp|temperature)/i.test(x)&&wheelPattern.test(x)&&!/(brake|disc|rotor)/i.test(x)),frontHeaders=tempHeaders.filter(x=>/(fl|fr|front)/i.test(x)),rearHeaders=tempHeaders.filter(x=>/(rl|rr|rear)/i.test(x)),pressureHeaders=h.filter(x=>/(press|psi)/i.test(x)&&wheelPattern.test(x)),wearHeaders=h.filter(x=>/wear/i.test(x)&&wheelPattern.test(x)),loadHeaders=h.filter(x=>/load/i.test(x)&&wheelPattern.test(x)),slipHeaders=h.filter(x=>/slip/i.test(x)&&wheelPattern.test(x));
  const points=[],speeds=[],allTemps=[];dataset.rows.forEach((row,i)=>{const x=finite(row[xHeader])?Number(row[xHeader]):i,fv=frontHeaders.map(k=>Number(row[k])).filter(Number.isFinite),rv=rearHeaders.map(k=>Number(row[k])).filter(Number.isFinite),av=tempHeaders.map(k=>Number(row[k])).filter(Number.isFinite);if(av.length)allTemps.push(...av);if(finite(row[speedHeader]))speeds.push(Number(row[speedHeader]));if(fv.length||rv.length)points.push({x,front:mean(fv),rear:mean(rv)});});
  const summary={rows:dataset.rows.length,xHeader,speedHeader,tempHeaders,pressureHeaders,wearHeaders,loadHeaders,slipHeaders,points,averageSpeed:mean(speeds),averageTemperature:mean(allTemps),minimumTemperature:allTemps.length?Math.min(...allTemps):NaN,maximumTemperature:allTemps.length?Math.max(...allTemps):NaN,mappingConfidence:tempHeaders.length>=4?"high":tempHeaders.length>=2?"medium":"low"};
  summary.conditions=conditionSummary(dataset,options.requestedConditions);summary.wear=wearAnalysis(dataset,options);summary.thermalDiagnostic=thermalDiagnostic(dataset,options);summary.datasetHeaders=h;summary._dataset=dataset;summary._lateRows=dataset.rows.slice(-Math.max(1,Math.ceil(dataset.rows.length*.20)));summary.pressureAudit=pressureAudit(summary,options);summary.comparisonMetrics=comparisonMetrics(dataset,summary);delete summary._dataset;delete summary._lateRows;return summary;
 }
 function parseIni(text){const out={};let section=null;String(text||"").replace(/^\uFEFF/,"").split(/\r?\n/).forEach(raw=>{const line=raw.trim();if(!line||line.startsWith(";")||line.startsWith("#"))return;const sm=line.match(/^\[([^\]]+)\]/);if(sm){section=sm[1].trim().toUpperCase();out[section]=out[section]||{};return;}if(!section||!line.includes("="))return;const pos=line.indexOf("="),key=line.slice(0,pos).trim().toUpperCase();out[section][key]=line.slice(pos+1).split(";")[0].trim();});return out;}
 function fileByBase(files,name){const key=Object.keys(files||{}).find(k=>basename(k)===String(name).toLowerCase());return key?{path:key,text:files[key]}:null;}
 function lengthKm(value){const text=String(value||"").replace(",",".");const m=text.match(/(\d+(?:\.\d+)?)\s*(km|m|mi|mile)/i);if(!m)return NaN;const x=Number(m[1]),u=m[2].toLowerCase();return u==="m"?x/1000:(u.startsWith("mi")?x*1.609344:x);}
 function parseTrackFiles(files,label){
  const ui=fileByBase(files,"ui_track.json"),surfaces=fileByBase(files,"surfaces.ini"),models=Object.keys(files||{}).filter(k=>/^models.*\.ini$/i.test(basename(k)));let meta={};try{if(ui)meta=JSON.parse(ui.text);}catch(e){}
  let len=lengthKm(meta.length),lengthSource=finite(len)?"ui_track.json":"unresolved";if(!finite(len))len=lengthKm(meta.description);if(finite(len)&&lengthSource==="unresolved")lengthSource="ui_track.json description";
  const s=parseIni(surfaces?.text||""),surfaceRows=Object.entries(s).filter(([k])=>/^SURFACE/.test(k)).map(([id,x])=>({id,key:x.KEY||id,friction:finite(x.FRICTION)?Number(x.FRICTION):NaN,damping:finite(x.DAMPING)?Number(x.DAMPING):0,wav:finite(x.WAV)?Number(x.WAV):0,sinHeight:finite(x.SIN_HEIGHT)?Number(x.SIN_HEIGHT):0,valid:String(x.IS_VALID_TRACK||"1")!=="0"}));
  const frictions=surfaceRows.filter(x=>x.valid&&finite(x.friction)).map(x=>x.friction),roughness=mean(surfaceRows.map(x=>Math.abs(x.wav)+Math.abs(x.sinHeight)*10).filter(Number.isFinite)),meanFriction=finite(mean(frictions))?mean(frictions):1.0,assumedLength=finite(len)?len:4.0,energyScore=clamp(0.52+assumedLength*0.105+(meanFriction-0.95)*0.7+(finite(roughness)?roughness:0)*0.035,0.55,1.75);
  return {label:label||meta.name||"Imported track",name:meta.name||label||"Imported track",country:meta.country||"",city:meta.city||"",lengthKm:assumedLength,lengthSource,surfaceCount:surfaceRows.length,meanFriction,roughness:finite(roughness)?roughness:0,modelFiles:models.length,energyScore,surfaces:surfaceRows,directEvidence:[ui?"track identity metadata":"track identity unavailable",surfaces?"surface physics parsed":"surface physics unavailable",finite(len)?"track length parsed":"track length fallback used"],inferredEvidence:["energy score combines length, mean surface friction and roughness","KN5 geometry, elevation and exact corner sequence are not decoded"]};
 }
 function simulateThermal(options){
  const track=options.track||{lengthKm:4,energyScore:1},laps=clamp(options.laps||10,1,200),avgSpeed=clamp(options.avgSpeed||120,20,350),ambient=clamp(options.ambient||20,-20,60),trackTemp=clamp(options.trackTemp||30,-10,90),aggression=clamp(options.aggression||1,0.5,1.6),lapTime=track.lengthKm/avgSpeed*3600,sink=(ambient+trackTemp)/2,rows=[];
  for(const comp of options.compounds||[])for(const axle of ["front","rear"]){const intensity=Number(axle==="front"?comp.loadF:comp.loadR)||11,target=Number(comp.target)||80,cooling=clamp(Number(comp.cool)||1,0.6,2.2);let temp=finite(options.blankets)&&Number(options.blankets)>0?Number(options.blankets):trackTemp,peak=temp,warmLap=null,series=[];for(let lap=1;lap<=laps;lap++){const heat=8.2*track.energyScore*aggression*(intensity/11)*Math.pow(Math.max(45,lapTime)/100,0.22),coolRate=clamp(0.115*cooling*Math.pow(100/Math.max(45,lapTime),0.16),0.055,0.28);temp+=heat-(temp-sink)*coolRate;peak=Math.max(peak,temp);if(warmLap===null&&Math.abs(temp-target)<=8)warmLap=lap;series.push({lap,temp:Number(temp.toFixed(2))});}const end=temp,status=peak>target+18?"overheat risk":end<target-12?"slow warm-up":"working-window candidate";rows.push({compound:comp.key,name:comp.name,axle,target,lapTime:Number(lapTime.toFixed(1)),warmLap,peak:Number(peak.toFixed(1)),end:Number(end.toFixed(1)),status,series});}
  return {model:"ACLM reduced-order screening model 1.0",track,laps,avgSpeed,ambient,trackTemp,aggression,rows,limitations:["not a lap-time solver","requires telemetry calibration","aero load is represented only through the selected FZ0 factor"]};
 }
 function balanceRecommendations(sim){const out=[],groups={};for(const row of sim?.rows||[]){groups[row.compound]=groups[row.compound]||{};groups[row.compound][row.axle]=row;}for(const [comp,g] of Object.entries(groups)){if(!g.front||!g.rear)continue;const delta=g.front.end-g.rear.end;out.push({compound:comp,delta:Number(delta.toFixed(1)),status:Math.abs(delta)<=5?"balanced screening result":"review axle balance",recommendation:Math.abs(delta)<=5?"retain baseline and validate telemetry":delta>0?"front hotter: inspect front pressure/camber/slip and brake heat; consider slightly more front cooling":"rear hotter: inspect rear pressure, driven slip and rear load; consider slightly more rear cooling"});}return out;}
 function pressureCamberSweep(options){const results=[],ideal=Number(options.idealHot)||27,ref=Number(options.referenceTemp)||26,target=Number(options.targetTemp)||80,basePressure=Number(options.coldPressure)||21,baseCamber=Number(options.camber)||-2,construction=options.construction||"radial",idealCamber=construction==="bias"?-1.4:-2.5;for(let dp=-3;dp<=3;dp++)for(let dc=-2;dc<=2;dc++){const cold=basePressure+dp,camber=baseCamber+dc*.5,hot=(cold+14.7)*(target+273.15)/(ref+273.15)-14.7,score=Math.abs(hot-ideal)*3+Math.abs(camber-idealCamber)*1.4;results.push({coldPsi:Number(cold.toFixed(1)),camberDeg:Number(camber.toFixed(1)),predictedHotPsi:Number(hot.toFixed(1)),score:Number(score.toFixed(2))});}return results.sort((a,b)=>a.score-b.score).slice(0,8);}
 function stintStrategy(options){const trackKm=Number(options.trackKm)||4,laps=Math.max(1,Number(options.laps)||20),out=[];for(const comp of options.compounds||[]){const life=Number(comp.lifeKm)||Math.max(40,trackKm*laps*.75),usable=Math.max(trackKm,life*.82),window=Math.max(1,Math.floor(usable/trackKm));out.push({compound:comp.key,name:comp.name,lifeKm:Number(life.toFixed(1)),recommendedLaps:window,stops:Math.max(0,Math.ceil(laps/window)-1),warmupLaps:comp.warmLap??null,confidence:Number(comp.lifeKm)>0?"class-life prior":"fallback estimate"});}return out;}
 function compareTirePacks(filesA,filesB){const a=fileByBase(filesA,"tyres.ini"),b=fileByBase(filesB,"tyres.ini");if(!a||!b)throw new Error("Both ZIPs must contain tyres.ini.");const ai=parseIni(a.text),bi=parseIni(b.text),sections=[...new Set([...Object.keys(ai),...Object.keys(bi)])].sort(),diffs=[];for(const section of sections){const keys=[...new Set([...Object.keys(ai[section]||{}),...Object.keys(bi[section]||{})])].sort();for(const key of keys){const av=ai[section]?.[key]??"",bv=bi[section]?.[key]??"";if(av!==bv)diffs.push({section,key,a:av,b:bv});}}return {sectionsA:Object.keys(ai).length,sectionsB:Object.keys(bi).length,differenceCount:diffs.length,differences:diffs.slice(0,250)};}
 function selectTestClass(classes,profile){const p=profile||{};return (classes||[]).find(c=>{const from=Number(c.from),to=Number(c.to);return (!Number.isFinite(from)||Number(p.year)>=from)&&(!Number.isFinite(to)||Number(p.year)<=to)&&(p.seriesKeywords||[]).some(k=>String(c.name||"").toLowerCase().includes(String(k).toLowerCase()));})||null;}
 const TEST_CARS=Object.freeze([
  {id:"escort_mk1_g2",name:"Ford Escort RS1600 Group 2",year:1972,mass:870,frontWeight:54,fzFactor:1.07,fw:.205,rw:.235,construction:"bias",seriesKeywords:["group 2","touring"],expected:"Front medium duty, rear light/medium boundary; period cross-ply race tire should warm progressively without a modern slick target."},
  {id:"lotus_49",name:"Lotus 49",year:1967,mass:500,frontWeight:40,fzFactor:1.05,fw:.190,rw:.250,construction:"bias",seriesKeywords:["formula","f1"],expected:"Light axle duty and slow hard-tire warm-up; bias-ply response should dominate."},
  {id:"porsche_917k",name:"Porsche 917K",year:1970,mass:800,frontWeight:42,fzFactor:1.18,fw:.260,rw:.360,construction:"bias",seriesKeywords:["prototype","sports"],expected:"Light static-width duty but meaningful speed load; track-energy and FZ factor sensitivity should be obvious."},
  {id:"bmw_e30_gpa",name:"BMW M3 E30 Group A",year:1989,mass:960,frontWeight:52,fzFactor:1.08,fw:.240,rw:.240,construction:"radial",seriesKeywords:["group a","touring"],expected:"Medium and relatively balanced axle duty; a useful baseline for temperature symmetry."},
  {id:"mclaren_f1_gtr",name:"McLaren F1 GTR",year:1995,mass:1120,frontWeight:43,fzFactor:1.15,fw:.265,rw:.315,construction:"radial",seriesKeywords:["bpr","gt1","le mans gt"],expected:"Medium duty with rear energy sensitivity; endurance compound should stabilize over a longer stint."},
  {id:"porsche_911_gt1",name:"Porsche 911 GT1",year:1998,mass:950,frontWeight:40,fzFactor:1.22,fw:.285,rw:.335,construction:"radial",seriesKeywords:["gt1","fia gt"],expected:"Front warm-up may lag the rear; speed-load factor materially changes the result."},
  {id:"mazda_787b",name:"Mazda 787B",year:1991,mass:830,frontWeight:43,fzFactor:1.22,fw:.300,rw:.355,construction:"radial",seriesKeywords:["group c","c1"],expected:"Low static-width duty with high circuit-energy dependence; validate using long-run telemetry."},
  {id:"formula_ford",name:"Formula Ford 1600",year:1970,mass:420,frontWeight:44,fzFactor:1.03,fw:.155,rw:.185,construction:"bias",seriesKeywords:["formula ford","junior"],expected:"Very light car but narrow tires; moderate N/mm duty and strong sensitivity to treaded-control construction."}
 ]);
 function researchPacket(entry,history){return {product:"ACLM Community Tire Research Submission",schemaVersion:"1.0.0",exportedUtc:new Date().toISOString(),entry,reviewHistory:history||[],policy:["publicly citeable evidence only","no confidential or proprietary information","maintainer review required before knowledge inclusion"]};}
 root.ACLMValidationCore={parseTelemetry,telemetrySummary,analyzeCalibrationFixture,comparePressureAB,COUPLED_NETWORK_DIAGNOSTIC,THERMAL_NETWORK_KEYS,PRESSURE_COMPLIANCE_KEYS,parseIni,parseTrackFiles,simulateThermal,balanceRecommendations,pressureCamberSweep,stintStrategy,compareTirePacks,selectTestClass,TEST_CARS,researchPacket};
})(typeof window!=="undefined"?window:globalThis);
