"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const WHEELS=["fl","fr","rl","rr"],ATM_PSI=14.6959;
function parseLine(line){const out=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){out.push(cell);cell="";}else cell+=c;}out.push(cell);return out;}
function loadCsv(file){const text=fs.readFileSync(file,"utf8"),lines=text.trimEnd().split(/\r?\n/),headers=parseLine(lines.shift()),rows=lines.map(line=>{const cells=parseLine(line),row={};for(let i=0;i<headers.length;i++)row[headers[i]]=cells[i]??"";return row;});return {text,headers,rows};}
function num(row,key){const value=Number(row?.[key]);return Number.isFinite(value)?value:NaN;}
function mean(values){const a=values.filter(Number.isFinite);return a.length?a.reduce((s,x)=>s+x,0)/a.length:null;}
function quantile(values,q){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+(a[Math.min(a.length-1,i+1)]-a[i])*f;}
function stats(values){const a=values.filter(Number.isFinite);return {count:a.length,mean:mean(a),p95:quantile(a,.95),min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null,first:a[0]??null,last:a.at(-1)??null};}
function regression(points){const pts=points.filter(p=>p.every(Number.isFinite));if(pts.length<2)return {count:pts.length,slope:null,intercept:null,correlation:null};const mx=mean(pts.map(p=>p[0])),my=mean(pts.map(p=>p[1])),sxx=pts.reduce((s,p)=>s+(p[0]-mx)**2,0),syy=pts.reduce((s,p)=>s+(p[1]-my)**2,0),sxy=pts.reduce((s,p)=>s+(p[0]-mx)*(p[1]-my),0);return {count:pts.length,slope:sxx?sxy/sxx:null,intercept:sxx?my-(sxy/sxx)*mx:null,correlation:sxx&&syy?sxy/Math.sqrt(sxx*syy):null};}
function classify(error){const e=Math.abs(error);return e<=.5?"PASS":e<=1.5?"REVIEW":"FAIL";}
function surfaceMean(row,wheel){return mean([num(row,`temp_inner_c_${wheel}`),num(row,`temp_middle_c_${wheel}`),num(row,`temp_outer_c_${wheel}`)]);}
function completeLapNumbers(rows){const groups=new Map();for(const row of rows){const lap=num(row,"lap"),pos=num(row,"normalized_track_position");if(!Number.isInteger(lap)||lap<1||!Number.isFinite(pos))continue;const g=groups.get(lap)||{count:0,min:Infinity,max:-Infinity};g.count++;g.min=Math.min(g.min,pos);g.max=Math.max(g.max,pos);groups.set(lap,g);}return [...groups].filter(([,g])=>g.count>=100&&g.min<=.12&&g.max>=.88).map(([lap])=>lap).sort((a,b)=>a-b);}
function lapMeans(rows,laps,keyFn){const wanted=new Set(laps),groups=new Map();for(const row of rows){const lap=num(row,"lap");if(!wanted.has(lap))continue;const value=keyFn(row);if(!Number.isFinite(value))continue;const a=groups.get(lap)||[];a.push(value);groups.set(lap,a);}return laps.filter(l=>groups.has(l)).map(l=>[l,mean(groups.get(l))]);}
function analyze(file,options={}){
 const idealPsi=Number(options.idealPsi)||28,lateFrom=Number(options.lateFrom)||30,lateTo=Number(options.lateTo)||33,wearDepartureThreshold=Number(options.wearDepartureThreshold)||99.999;
 const {text,rows}=loadCsv(file);if(!rows.length)throw new Error("Telemetry CSV has no rows.");const first=rows[0],last=rows.at(-1),completeLaps=completeLapNumbers(rows),slopeLaps=completeLaps.slice(-10),lateRows=rows.filter(r=>{const lap=num(r,"lap");return lap>=lateFrom&&lap<=lateTo;});
 const startDistance=num(first,"tire_set_distance_m"),endDistance=num(last,"tire_set_distance_m"),perWheel={};
 for(const wheel of WHEELS){
  const pressureKey=`pressure_psi_${wheel}`,coreKey=`core_temp_c_${wheel}`,wearKey=`wear_raw_${wheel}`;
  const pressureCore=regression(rows.map(r=>[num(r,coreKey),num(r,pressureKey)]));
  const firstDeparture=rows.find(r=>num(r,wearKey)<wearDepartureThreshold);
  const pressureLate=stats(lateRows.map(r=>num(r,pressureKey))),coreLate=stats(lateRows.map(r=>num(r,coreKey))),surfaceLate=stats(lateRows.map(r=>surfaceMean(r,wheel)));
  const pressureLapRegression=regression(lapMeans(rows,slopeLaps,r=>num(r,pressureKey))),coreLapRegression=regression(lapMeans(rows,slopeLaps,r=>num(r,coreKey)));
  perWheel[wheel]={
   startingPressurePsi:num(first,pressureKey),startingCoreC:num(first,coreKey),referencePressureAt26CFromRegressionPsi:Number.isFinite(pressureCore.intercept)&&Number.isFinite(pressureCore.slope)?pressureCore.intercept+pressureCore.slope*26:null,pressureCoreRegression:pressureCore,
   latePressurePsi:pressureLate,pressureErrorPsi:pressureLate.mean-idealPsi,pressureClassification:classify(pressureLate.mean-idealPsi),lateCoreC:coreLate,lateSurfaceMeanC:surfaceLate,
   lateSurfaceChannelCombinedC:stats(lateRows.flatMap(r=>[num(r,`temp_inner_c_${wheel}`),num(r,`temp_middle_c_${wheel}`),num(r,`temp_outer_c_${wheel}`)])),
   coreSlopeCPerLap:coreLapRegression.slope,pressureSlopePsiPerLap:pressureLapRegression.slope,slopeLapWindow:slopeLaps,
   wear:{start:num(first,wearKey),end:num(last,wearKey),delta:num(last,wearKey)-num(first,wearKey),firstDepartureThreshold:wearDepartureThreshold,firstDepartureDistanceKm:firstDeparture?num(firstDeparture,"tire_set_distance_m")/1000:null,firstDepartureLap:firstDeparture?num(firstDeparture,"lap"):null}
  };
 }
 const front=(perWheel.fl.latePressurePsi.mean+perWheel.fr.latePressurePsi.mean)/2,rear=(perWheel.rl.latePressurePsi.mean+perWheel.rr.latePressurePsi.mean)/2;
 const coreStable=WHEELS.every(w=>Math.abs(perWheel[w].coreSlopeCPerLap)<.10),pressureStable=WHEELS.every(w=>Math.abs(perWheel[w].pressureSlopePsiPerLap)<.03);
 const compounds=[...new Set(rows.map(r=>String(r.compound||"").trim()).filter(Boolean))];
 return {schema:"ACLM long-duration telemetry calibration analysis 1.0",fixtureId:options.fixtureId||null,file:path.basename(file),csvSha256:crypto.createHash("sha256").update(text).digest("hex"),samples:rows.length,configuredLoggerRateHz:Number(options.configuredLoggerRateHz)||10,effectiveObservedSampleRateHz:rows.length>1?1000/(mean(rows.slice(1).map((r,i)=>num(r,"elapsed_ms")-num(rows[i],"elapsed_ms")))):null,startTimestampUtc:first.timestamp_utc,endTimestampUtc:last.timestamp_utc,car:first.car,track:first.track,observedCompoundStrings:compounds,liveCompoundDecision:compounds.length===1?compounds[0]:"MULTIPLE / REVIEW",lapStart:num(first,"lap"),lapEnd:num(last,"lap"),completeLaps,distance:{basis:"CURRENT_TIRE_SET_DISTANCE",startM:startDistance,endM:endDistance,spanKm:(endDistance-startDistance)/1000},conditions:{airC:stats(rows.map(r=>num(r,"air_temp_c"))),roadC:stats(rows.map(r=>num(r,"road_temp_c"))),requestedWearMultiplier:Number(options.requestedWearMultiplier)||1,rawAidTireRate:[...new Set(rows.map(r=>num(r,"aid_tire_rate")).filter(Number.isFinite))],aidTireRateInterpretation:"UNKNOWN; zero is not evidence that wear was disabled"},pressure:{idealPsi,lateLapWindow:[lateFrom,lateTo],perWheel:Object.fromEntries(WHEELS.map(w=>[w,{meanPsi:perWheel[w].latePressurePsi.mean,errorPsi:perWheel[w].pressureErrorPsi,classification:perWheel[w].pressureClassification}])),axle:{front:{meanPsi:front,errorPsi:front-idealPsi,classification:classify(front-idealPsi)},rear:{meanPsi:rear,errorPsi:rear-idealPsi,classification:classify(rear-idealPsi)}},architectureClassification:"REFERENCE-AXLE LIVE PASS ON ACTUAL APPROXIMATELY 24F/24R SESSION STATE",generated24F25RRecommendationStatus:"NOT YET LIVE-VALIDATED",perCornerCorrectionsAuthorized:false},thermal:{historicalPassFail:"UNRESOLVED",lateLapWindow:[lateFrom,lateTo],slopeLapWindow:slopeLaps,coreSlopeThresholdCPerLap:.10,pressureSlopeThresholdPsiPerLap:.03,coreStable,pressureStable,stabilizationClassification:coreStable&&pressureStable?"ENGINEERING STABILITY SCREEN PASS":"NOT STABILIZED",interpretation:"Cool mean cores and surfaces coexist with active transient tread heating. Do not infer universally insufficient friction heat and do not retune Thermal V2 from this run alone."},wear:{fixtureId:"GT40-LONG-RUN-WEAR-FIXTURE-001",evidenceClass:"SIMULATOR TELEMETRY / CALIBRATION FIXTURE",historicalCalibrationStatus:"UNRESOLVED — STORE, DO NOT FIT",realKmToVirtualKmMappingAuthorized:false,useLoadRetained:true},perWheel};
}
if(require.main===module){const file=process.argv[2];if(!file)throw new Error("Usage: node analyze_long_run_telemetry.js <csv> [idealPsi]");process.stdout.write(JSON.stringify(analyze(file,{idealPsi:Number(process.argv[3])||28,fixtureId:"GT40-LONG-RUN-001",requestedWearMultiplier:1}),null,2)+"\n");}
module.exports={analyze};
