"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const wheels=["fl","fr","rl","rr"];
function parseLine(line){const out=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){out.push(cell);cell="";}else cell+=c;}out.push(cell);return out;}
function load(file){const text=fs.readFileSync(file,"utf8"),lines=text.trimEnd().split(/\r?\n/),headers=parseLine(lines.shift()),rows=lines.map(line=>{const values=parseLine(line),row={};for(let i=0;i<headers.length;i++)row[headers[i]]=values[i];return row;});return {file:path.basename(file),sha256:crypto.createHash("sha256").update(text).digest("hex"),rows};}
function number(row,key){const x=Number(row[key]);return Number.isFinite(x)?x:NaN;}
function quantile(values,q){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+(a[Math.min(i+1,a.length-1)]-a[i])*f;}
function stats(values){const a=values.filter(Number.isFinite);if(!a.length)return {count:0,mean:null,p95:null,min:null,max:null,latest:null};return {count:a.length,mean:a.reduce((s,x)=>s+x,0)/a.length,p95:quantile(a,.95),min:Math.min(...a),max:Math.max(...a),latest:a[a.length-1]};}
function slope(rows,key,xKey="tire_set_distance_m"){const pts=rows.map(r=>[number(r,xKey)/1000,number(r,key)]).filter(p=>p.every(Number.isFinite));if(pts.length<2)return null;const mx=pts.reduce((s,p)=>s+p[0],0)/pts.length,my=pts.reduce((s,p)=>s+p[1],0)/pts.length,den=pts.reduce((s,p)=>s+(p[0]-mx)**2,0);return den?pts.reduce((s,p)=>s+(p[0]-mx)*(p[1]-my),0)/den:null;}
function summarize(files){
 const loaded=files.map(load),rows=loaded.flatMap(x=>x.rows).sort((a,b)=>number(a,"logger_cumulative_distance_m")-number(b,"logger_cumulative_distance_m")||String(a.timestamp_utc).localeCompare(String(b.timestamp_utc))),dedup=[];let prior=null;
 for(const row of rows){const key=`${row.timestamp_utc}|${row.packet_id}`;if(key!==prior)dedup.push(row);prior=key;}
 const first=dedup[0],last=dedup.at(-1),startM=number(first,"logger_cumulative_distance_m"),endM=number(last,"logger_cumulative_distance_m"),tailStart=endM-1000,tail=dedup.filter(r=>number(r,"logger_cumulative_distance_m")>=tailStart),surface={};
 for(const wheel of wheels){const allSurface=tail.flatMap(r=>[number(r,`temp_inner_c_${wheel}`),number(r,`temp_middle_c_${wheel}`),number(r,`temp_outer_c_${wheel}`)]);surface[wheel]={combined:stats(allSurface),inner:stats(tail.map(r=>number(r,`temp_inner_c_${wheel}`))),middle:stats(tail.map(r=>number(r,`temp_middle_c_${wheel}`))),outer:stats(tail.map(r=>number(r,`temp_outer_c_${wheel}`)))};}
 const perWheel={};for(const wheel of wheels)perWheel[wheel]={pressurePsi:stats(tail.map(r=>number(r,`pressure_psi_${wheel}`))),pressureSlopePsiPerKm:slope(tail,`pressure_psi_${wheel}`,"logger_cumulative_distance_m"),coreC:stats(tail.map(r=>number(r,`core_temp_c_${wheel}`))),coreSlopeCPerKm:slope(tail,`core_temp_c_${wheel}`,"logger_cumulative_distance_m"),surfaceC:surface[wheel],loadN:stats(tail.map(r=>number(r,`wheel_load_n_${wheel}`))),slipRaw:stats(tail.map(r=>number(r,`wheel_slip_raw_${wheel}`))),wearRaw:{first:number(first,`wear_raw_${wheel}`),last:number(last,`wear_raw_${wheel}`),delta:number(last,`wear_raw_${wheel}`)-number(first,`wear_raw_${wheel}`)}};
 const latestPressure=Object.fromEntries(wheels.map(w=>[w,number(last,`pressure_psi_${w}`)])),latestCore=Object.fromEntries(wheels.map(w=>[w,number(last,`core_temp_c_${w}`)]));
 const axle={front:{pressurePsi:(latestPressure.fl+latestPressure.fr)/2,idealPsi:27},rear:{pressurePsi:(latestPressure.rl+latestPressure.rr)/2,idealPsi:27}};for(const a of Object.values(axle)){a.errorPsi=a.pressurePsi-a.idealPsi;a.classification=Math.abs(a.errorPsi)<=.5?"PASS":Math.abs(a.errorPsi)<=1.5?"REVIEW":"FAIL";}
 return {schema:"ACLM telemetry evidence analysis 1.0",files:loaded.map(x=>({file:x.file,sha256:x.sha256,rows:x.rows.length,firstTimestamp:x.rows[0]?.timestamp_utc,lastTimestamp:x.rows.at(-1)?.timestamp_utc,startLoggerDistanceM:number(x.rows[0],"logger_cumulative_distance_m"),endLoggerDistanceM:number(x.rows.at(-1),"logger_cumulative_distance_m"),spanKm:(number(x.rows.at(-1),"logger_cumulative_distance_m")-number(x.rows[0],"logger_cumulative_distance_m"))/1000})),combined:{rows:dedup.length,startTimestamp:first.timestamp_utc,endTimestamp:last.timestamp_utc,startLoggerDistanceM:startM,endLoggerDistanceM:endM,spanKm:(endM-startM)/1000,lapStart:number(first,"lap"),lapEnd:number(last,"lap"),airC:stats(dedup.map(r=>number(r,"air_temp_c"))),roadC:stats(dedup.map(r=>number(r,"road_temp_c"))),speedKmh:stats(dedup.map(r=>number(r,"speed_kmh"))),rawAidTireRate:[...new Set(dedup.map(r=>number(r,"aid_tire_rate")).filter(Number.isFinite))],lastKmRows:tail.length,latestPressurePsi:latestPressure,latestCoreC:latestCore,axlePressureClosure:axle,perWheel}};
}
if(require.main===module){if(process.argv.length<3)throw new Error("Usage: node analyze_telemetry_csv.js <csv> [csv ...]");process.stdout.write(JSON.stringify(summarize(process.argv.slice(2)),null,2)+"\n");}
module.exports={summarize};
